### ISSUE TITLE
Warn about systemd vs varnishncsa -F

### ISSUE THREAD

**Issue by Dridi** [varnishcache/pkg-varnish-cache#101]
We should add a comment in our `varnishncsa.service` warning about changing the default format: percent signs need to be doubled (escaped) because they may be interpreted by systemd as well.

**Comment by dmatetelki** [comment]
@Dridi : i cannot find a `varnishncsa.service` file with the `%` sign in it in any branch.

**Comment by gquintard** [comment]
I don't think there's one, but the idea is that people may change the
default format and will introduce % signs, so we have to warn them

-- 
Guillaume Quintard

**Comment by Dridi** [comment]
What @gquintard said ;-)

I opened this ticket last time I saw an end-user fall into this trap and forgot about it.

**Comment by Dridi** [comment]
Back-ported to 6.x: 22af57c
