### ISSUE TITLE
Can not add repository (DrupalVM, vagrant_box: geerlingguy/ubuntu1804)

### ISSUE THREAD

**Issue by homeandr777** [varnishcache/pkg-varnish-cache#102]
TASK [geerlingguy.varnish : include_tasks] *************************************
included: /vagrant/provisioning/roles/geerlingguy.varnish/tasks/setup-Debian.yml for drupalvm

TASK [geerlingguy.varnish : Ensure APT HTTPS Transport is installed.] **********
changed: [drupalvm]

TASK [geerlingguy.varnish : Add packagecloud.io Varnish apt key.] **************
changed: [drupalvm]

TASK [geerlingguy.varnish : Add packagecloud.io Varnish apt repository.] *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu bionic Release' does not have a Release file.
fatal: [drupalvm]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ARMCpS/ansible_module_apt_repository.py\", line 551, in <module>\n    main()\n  File \"/tmp/ansible_ARMCpS/ansible_module_apt_repository.py\", line 543, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 505, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu bionic Release' does not have a Release file.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.postfix : restart postfix] ************************

RUNNING HANDLER [geerlingguy.nginx : restart nginx] ****************************

RUNNING HANDLER [geerlingguy.nginx : reload nginx] *****************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=188  changed=76   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by fgsch** [comment]
Bionic is not currently supported. See #100

**Comment by DougBatesOLT** [comment]
Sorry, I'm a little unclear. Varnish 5.2.1 can be installed  directly via apt in Ubuntu 18.04 (bionic). 

```
sudo apt install varnish
...
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 libvarnishapi1 amd64 5.2.1-1 [64.1 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 varnish amd64 5.2.1-1 [708 kB]
```

However, those of us using packagecloud.io via popular tools like Drupal-VM cannot include varnish in our Ubuntu 18.04 builds. 

`E:The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu bionic Release' does not have a Release file.`

What would it take to include the supported version on "the official repository for varnish-cache.org packages" so we can use these tools as intended?
