### ISSUE TITLE
Varnish 6.0 Packages for Ubuntu 18.04 LTS (Bionic)

### ISSUE THREAD

**Issue by juancybexmedia** [varnishcache/pkg-varnish-cache#103]
I tried to install Varnish 6.0 using the following sources for Ubuntu 18.04 LTS
```
deb https://packagecloud.io/varnishcache/varnish60/ubuntu/ bionic main
deb-src https://packagecloud.io/varnishcache/varnish60/ubuntu/ bionic main
```
But I'm getting the following error when trying to run apt-get update:
`The repository 'https://packagecloud.io/varnishcache/varnish60/ubuntu bionic Release' does not have a Release file.`

Thanks in advance for your help.

**Comment by fgsch** [comment]
Duplicated of #100
