### ISSUE TITLE
varnishreload fails for large vcl files

### ISSUE THREAD

**Issue by TomVanBerlo** [varnishcache/pkg-varnish-cache#104]
When you have a large vcl file, the reload script will fail with a truncated error message. 
```
[response was truncated]

Command failed with error code 201
```
This is caused by the [cli-limit ](https://varnish-cache.org/docs/trunk/reference/varnishd.html#cli-limit) of varnish.

The last part of the varnishadm vcl.show -v command output is not needed in the script, so I solved the issue with the following code. It checks if the reason for the failure is the truncated error.

```diff --git a/varnishreload b/varnishreload
index cb865fa..49abe3a 100755
--- a/varnishreload
+++ b/varnishreload
@@ -38,6 +38,9 @@ WORK_DIR=

 SCRIPT="$0"

+tmp_file='/tmp/varnishreload-err.tmp'
+allowed_err='Command failed with error code 201'
+
 usage() {
        test $# -eq 1 &&
        printf 'Error: %s.\n\n' "$1"
@@ -112,7 +115,8 @@ find_label_ref() {
 }

 find_vcl_file() {
-       VCL_SHOW=$(varnishadm vcl.show -v "$VCL_NAME") ||
+       VCL_SHOW=$(command varnishadm -n "$WORK_DIR" -- vcl.show -v "$VCL_NAME" 2> "$tmp_file")||
+       grep -q "$allowed_err" "$tmp_file" ||
        fail "failed to get the VCL file name"

        echo "$VCL_SHOW" |
```

**Comment by Dridi** [comment]
Thanks for such an amazing bug report! I'm not taking the patch as-is, but it will sure serve as a starting point for a more sustainable solution. I'm not sure we can guarantee that error messages such as "Command failed with error code XXX" will stay stable over time.

Quite the corner case :)

**Comment by Dridi** [comment]
I think I'm going for this to stay consistent with how the script reports errors in other places:

```diff
diff --git i/systemd/varnishreload w/systemd/varnishreload
index cb865fa..e6e6a9e 100755
--- i/systemd/varnishreload
+++ w/systemd/varnishreload
@@ -112,15 +112,23 @@ find_label_ref() {
 }
 
 find_vcl_file() {
-       VCL_SHOW=$(varnishadm vcl.show -v "$VCL_NAME") ||
-       fail "failed to get the VCL file name"
-
-       echo "$VCL_SHOW" |
-       awk '$1 == "//" && $2 == "VCL.SHOW" {print; exit}' | {
-               # all this ceremony to handle blanks in FILE
-               read -r DELIM VCL_SHOW INDEX SIZE FILE
-               echo "$FILE"
-       }
+       VCL_SHOW=$(varnishadm vcl.show -v "$VCL_NAME" 2>&1) || :
+       VCL_FILE=$(
+               echo "$VCL_SHOW" |
+               awk '$1 == "//" && $2 == "VCL.SHOW" {print; exit}' | {
+                       # all this ceremony to handle blanks in FILE
+                       read -r DELIM VCL_SHOW INDEX SIZE FILE
+                       echo "$FILE"
+               }
+       ) || :
+
+       if [ -z "$VCL_FILE" ]
+       then
+               echo "$VCL_SHOW" >&2
+               fail "failed to get the VCL file name"
+       fi
+
+       echo "$VCL_FILE"
 }
 
 find_vcl_reloads() {
```

Could you please give it a try? I think I will come up with the test suite I was going to write if this got integrated upstream because otherwise it's going to decay as Varnish moves forward.

**Comment by TomVanBerlo** [comment]
The code works fine on large vcl files. No more errors. 
Thanks.

**Comment by ooprala** [comment]
I've created a pull request #134, which is basically a follow up to the code fix in @Dridi's [comment](https://github.com/varnishcache/pkg-varnish-cache/issues/104#issuecomment-409935465). Many more details are in the PR itself. Thanks

**Comment by gquintard** [comment]
garbage collecting this issue
