### ISSUE TITLE
Add TasksMax=infinity to varnish.service

### ISSUE THREAD

**Issue by Dridi** [varnishcache/pkg-varnish-cache#118]
That is, if all the platforms we target have a recent-enough systemd that supports this entry. Someone:tm: should have a look and do some testing. It would land in the weekly packages first and then 6.0 if it's safe to back-port.

See https://github.com/varnishcache/varnish-cache/issues/2822.

**Comment by daghf** [comment]
6.0/LTS build from the 6.x branch, right?

If that is the case, we seem to already have this in place:

https://github.com/varnishcache/pkg-varnish-cache/blob/6c90eb775857573564dc1fe38424267143bb6b34/systemd/varnish.service#L19

**Comment by Dridi** [comment]
Thank you for compensating my lack of sleep today, case closed :)
