### ISSUE TITLE
varnishreload manpage is missing

### ISSUE THREAD

**Issue by uhliarik** [varnishcache/pkg-varnish-cache#119]
varnishreload manpage is missing. Could you please supply it?

**Comment by Dridi** [comment]
Hello,

Thank you for your interest in `varnishreload`. My first question would be why you need a manual for it, isn't `varnishreload -h` enough?

**Comment by uhliarik** [comment]
> Hello,
> 
> Thank you for your interest in `varnishreload`. My first question would be why you need a manual for it, isn't `varnishreload -h` enough?

Hello Dridi. I'm maintainer of Varnish in Fedora/RHEL, so this is not help for me. `varnishreload -h` indeed prints nice help, but I think it would be better, if we have also manpage (1) for this, since all other binaries/scripts have one. This would be only one binary, which don't have manpage :(. If you don't have enough time for such things, I can prepare .rst file and create PR.

**Comment by Dridi** [comment]
No worries, I'm also a package maintainer for Fedora so I will help you comply with guidelines and bring the question of a manual to the team. Traditionally in the Varnish project we use `rst2man` to build manuals, would you like to attempt redacting one? I would happily take care of the integration in our packages here and should you need my help, on the Fedora/RHEL side too on my own time.

**Comment by uhliarik** [comment]
Dridi, thanks for your quick response. I will try to prepare some short RST file for `varnishreload` containing mainly information from `varnishreload -h` and/or README/RELEASE if there is any (I'll check). 

It would be best, if you can integrate it in upstream here (github), and I will then merge it with Fedora/RHEL packages.

**Comment by Dridi** [comment]
ETIMEDOUT
