### ISSUE TITLE
RPM Package does not generate /etc/varnish/secret anymore

### ISSUE THREAD

**Issue by ayoubumoru1999** [varnishcache/pkg-varnish-cache#120]
For some reason the secret file generation got removed from the package.

This is not a documented change, is this by accident or is there a reason behind it?

**Varnish 6.0 - RPM**
`
test -f /etc/varnish/secret || (uuidgen > /etc/varnish/secret && chmod 0600 /etc/varnish/secret)`

**Varnish 6.1 - RPM**
`/bin/systemctl daemon-reload >/dev/null 2>&1 || :
chown varnishlog:varnish /var/log/varnish/
/sbin/ldconfig
`

**Comment by Dridi** [comment]
It is a documented change:

https://varnish-cache.org/docs/6.0/whats-new/upgrading-6.0.html#packaging-changes

> To stay on the topic of the command line interface, packages no longer create a secret file for the CLI, and services omit `-S` and `-T` options on the `varnishd` command. This means that out of the box, you can only connect to the CLI locally with enough privileges to read a secret generated randomly. This means less noise in our packages, and you need to change the service configuration to enable remote access to the CLI. With previous packages, you also needed to change your configuration because the CLI would only listen to the loopback interface anyway.

But we accidentally used the old packaging for the 6.0.0 release and fixed it first in 6.1, then in 6.0.2:

https://varnish-cache.org/lists/pipermail/varnish-announce/2018-November/000731.html

Unless you need a specific feature from Varnish 6.1, we recommend to stay on 6.0 as explained for the 6.0.2 release. New non-breaking features find their way in the 6.0 series. Don't hesitate to register to our varnish-announce mailing list, it's a very low traffic list with mostly releases and again, apologies for the inconvenience.
