### ISSUE TITLE
Packagecloud repository gone

### ISSUE THREAD

**Issue by durzo** [varnishcache/pkg-varnish-cache#125]
All the packagecloud repo links ( everything under https://packagecloud.io/varnishcache ) have stopped working, they now return a 404.

**Comment by akira-miyamoto** [comment]
I am facing same issue.
Was there official announcement that varnish comm stops using packagecloud ?

**Comment by caseyfw** [comment]
@akira-miyamoto not that I can see. By the looks of it, their packagecloud.io account has just ran out of credit. Anyone have a copy of the varnish-4.1.11-1.el6.x86_64.rpm lying around...?

**Comment by espebra** [comment]
Sorry about this. It has been fixed now. Closing.
