### ISSUE TITLE
debian buster

### ISSUE THREAD

**Issue by hjanuschka** [varnishcache/pkg-varnish-cache#127]
hi there ✋ 

thx for packaging varnish up via packagecloud, can you please add  debian:buster  support?

i would do a PR - but have no clou how packagecloud packaging works :'(

**Comment by Dridi** [comment]
There is nothing to change in this repository to add debian 10 support, I just confirmed this by doing a local build. For packagecloud repositories, this is outside of the scope for this code base as supporting a new OS implies some QA beforehand.

I assume we will eventually announce buster support via our usual channels.

**Comment by bzed** [comment]
@Dridi any news on that? buster was released some longish time ago now, and there is still no support for it :-(

**Comment by gquintard** [comment]
@bzed did you try the buster weeklies (https://packagecloud.io/varnishcache/varnish-weekly)?

We want to build confidence before releasing proper packages, so your feedback is welcome.

**Comment by dugwood** [comment]
@gquintard I'll try those packages too, but is there a planned release date?

Also, is there a way to know if the package has changed from one week to another? As it's the same source code I imagine, so the only changes would be in the packaging itself (configuration files, bash scripts...).

**Comment by gquintard** [comment]
@dugwood my plan is to have the next release have `buster` support. So February 15th at the latest is `6.3` doesn't see a revision release.

**Comment by jeffdesc** [comment]
@gquintard is this still planned to be released the 15th of February 2020? We do need Varnish 6.3 for Debian 10 really fast and are awaiting for this one.

Thanks for your feedback.

**Comment by gquintard** [comment]
@jeffdesc, my bad, the next release is in March, not February. This will be 6.4 or 7.0, there's no plan to support 6.3.
You can get weekly packages for it though

**Comment by jeffdesc** [comment]
@gquintard thanks for your feedback. Where can I find the Debian 10 packages for 6.3 or 6.0? This in a packaged form of course.

**Comment by gquintard** [comment]
At the moment, there are none. `buster` repos have `6.1`, and the packagecloud.io repos will get the next release on march 15th (or really soon after), the `6.0` fate hasn't been decided but it's likely it will also get `buster` support.

**Comment by jeffdesc** [comment]
Yes, unfortunately the 6.1 is EOL already according to Varnish's site. Rather we don't install EOL software on production grade systems.

So the earliest is only March having Debian 10 support? @gquintard

**Comment by gquintard** [comment]
Yes, that is correct. Note that the Enterprise version should get buster
support in the coming days if you are really in a hurry.

Or you should be able to build packages yourself following the circleci
recipes

**Comment by jeffdesc** [comment]
@gquintard thanks for the feedback. We'll have a look internally.

**Comment by krillerdk** [comment]
I just tried building buster packages locally from the instructions. I updated the build-depends to make sure I got python3-versions:
python-sphinx -> python3-sphinx
python-docbase -> python3-docbase.

That ended up producing a package that seems valid and installs without problems on Buster.

**Comment by gquintard** [comment]
good to hear, just note that 6.4 is available on buster: https://packagecloud.io/varnishcache/varnish64

**Comment by krillerdk** [comment]
yes, I saw that. I'd still like to see official LTS-packges for Buster.

I'm not sure it was clear from my previous comment: What I built was 6.0.6 from the weekly branch on Buster. Just wanted to make sure that information was here as well.

Do you have any updated timeline on when we might see official LTS packages for Buster in the repository?

**Comment by gquintard** [comment]
This is currently not planned. Buster has upgraded the `jemalloc` package, a central part of our memory management and that kind of change doesn't fit inside an LTS as the behavior is quite different from the old one.
