### ISSUE TITLE
Debian Buster support

### ISSUE THREAD

**Issue by HOSTED-POWER** [varnishcache/pkg-varnish-cache#128]
Hi,

Since Debian 10.1 is out now and Debian 10 itself is released for over 2 months now, it would be great if we could install varnish 6.2.x on it trough packagecloud repo.

We tried to installed today and were a bit surprised there was no way we could deploy it :)

**Comment by HOSTED-POWER** [comment]
Any update on this perhaps? 

We managed to use ubuntu repo and install libjemalloc from somewhere else, but not the cleanest solution :)

**Comment by gquintard** [comment]
Hi,

yes, `debian:buster` weekliepackages are now automatically built, but they are not published at the moment.

After some time, once we are confident with the weeklies we'll push the official releases

**Comment by Dridi** [comment]
@gquintard, I think we can push the weeklies, they are by definition experimental and use-at-your-own-risk packages. And they are exactly the kind of packages we want people to play with before we discover problems.

@HOSTED-POWER if you really need packages, you can follow the build instructions and produce your own packages. I was able to confirm that they build fine last July.

**Comment by HOSTED-POWER** [comment]
So is buster now supported or not yet? :)

Still don't seem to find them here: https://packagecloud.io/app/varnishcache/varnish63/search

**Comment by dugwood** [comment]
@HOSTED-POWER see https://github.com/varnishcache/pkg-varnish-cache/issues/127#issuecomment-564431831

**Comment by idl0r** [comment]
Can you please re-open that issue until it's really fixed, @Dridi?

**Comment by Dridi** [comment]
Let me clarify what I closed: buster support with our packaging scripts. Like I said in https://github.com/varnishcache/pkg-varnish-cache/issues/127#issuecomment-511117872 it works out of the box with the 6.x and weekly branches in their current states. So anyone can create packages for Debian 10 with this repository.

What everyone seems to ask about is buster packages in packagecloud repositories and is a different matter. If you want to track packagecloud updates here, we can do that, I'll let @gquintard reopen if he thinks it's relevant.

**Comment by gquintard** [comment]
> If you want to track packagecloud updates here, we can do that

no opinion

**Comment by idl0r** [comment]
Yes, it's about packagecloud.
@gquintard is anything blocking buster packages, can we help somehow?

**Comment by gquintard** [comment]
Hi Christian,

Feedback on the weekly packages would be nice, specially since the
libjemalloc version got updated for this debian version.

Apart from that, the plan is to flip the switch with the 6.4 varnish
release mid-march.
