### ISSUE TITLE
Packaged varnishlog setup is incomplete

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#13]
We currently ship an init script/service file to start varnishlog. This is not enabled by default.

If someone enables it with default config, they will get a binary VSL dump in `/var/log/varnish/varnish.log` which most likely will fill their hard drive within a day. (on my debian jessie system)

I'm assuming the original thought here was that server errors should be logged, so the sysadmin can handle them. I guess logging "all" traffic for a single URL could be another use case?

1) First of all, it is sub-optimal that the near-default config will fill the disk and stop everything. We need to handle that somehow. Sampling or token-bucket based rate limiting have been suggested before. (I don't see increasing logrotate interval as very viable.)

2) Are we really expecting that people use our tool to read the logs in /var/log/? Shouldn't they be in ASCII format by default, like every other log in there? (=> add -A to the default invocation)

3) We should also provide examples of VSL queries that can be useful.  My quick hack is using `RespStatus ~ "^(40[^4]|50.)"` but that is probably too wide for most systems.
(as in: `/usr/bin/varnishlog -a -A -w /var/log/varnish/varnish.log -D -P /run/varnishlog/varnishlog.pid -q RespStatus ~ "^(40[^4]|50.)"` )

Input welcome.

**Comment by ingvarha** [comment]
My thoughts:

1) That /var/log gets filled on a busy site should not be a surprise. Apache will also fill the log partition if the site is busy enough. Proper log rotation takes care of this. Setting up log rotation is a common sysadmin task. We have had at least a couple of busy sites that dumps the full binary log to disk, and have had good use for that when debugging later on. A warning in the docs, and even in the startup stdout/stderr/log, could be handy, though.

2) Well, there are other daemons putting binary logs in /var/log. systemd's binary journal is put there.  mysql's binary log is often put there. Are there any LSB or other standardization that says only clear-text logs in /var/log ?

3) Absolutely. Add examples to the docs or the man page.

Ingvar

**Comment by tfheen** [comment]
]] Lasse Karstensen 

> 1) First of all, it is sub-optimal that the near-default config will
> fill the disk and stop everything. We need to handle that somehow.
> Sampling or token-bucket based rate limiting have been suggested
> before. (I don't see increasing logrotate interval as very viable.)

I agree on this, varnish logs are very, very verbose.  Delegate the
.service file to /usr/share/doc/varnish/examples?  I can see the point
of shipping varnishncsa so it's trivial to enable, but full logs for all
of varnish is uncommon, I'd think.

> 2) Are we really expecting that people use our tool to read the logs
> in /var/log/? Shouldn't they be in ASCII format by default, like every
> other log in there? (=> add -A to the default invocation)

I think asking folks to use varnishlog is reasonable, since it provides
better filtering tools.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by ssm** [comment]
Moving varnishlog.service to /usr/share/doc/varnish/examples is a good idea.  I think I'll do that for the packaging in Debian as well.

**Comment by lkarsten** [comment]
Reviewed for 4.1.3 packaging:

In Debian's pkg-varnish.git the change removing the varnishlog.service file is:
https://anonscm.debian.org/git/pkg-varnish/pkg-varnish.git/commit/?id=0b9cd9a54b2c7b6aaa5afd30e3311749bf84a070

Not implementing this in our packages this late in 4.1. We can revisit if for 5.0 if we think it important.

**Comment by denisbr** [comment]
@lkarsten the varnishlog stuff was removed for 4.1.x after all, right?

**Comment by denisbr** [comment]
Closing this issue, varnishlog.service was removed from the package in 4.1.4.
