### ISSUE TITLE
Conclicts warning CENTOS 6.x

### ISSUE THREAD

**Issue by influenist** [varnishcache/pkg-varnish-cache#136]
Hi,

Please advise:
```
varnish-4.0.4-1.el6.x86_64 has installed conflicts varnish-libs: varnish-4.0.4-1.el6.x86_64
varnish-4.0.4-1.el6.x86_64 has installed conflicts varnish-docs: varnish-4.0.4-1.el6.x86_64
varnish-4.0.4-1.el6.x86_64 has installed conflicts varnish-debuginfo: varnish-4.0.4-1.el6.x86_64
```

**Comment by Dridi** [comment]
We no longer support Varnish 4.0 and no longer produce packages for CentOS 6, and we haven't for a long time already.

I'm not sure what other piece of advice we can give other than upgrading to CentOS 7 and Varnish 6.0 LTS.
