### ISSUE TITLE
RFC: master branch vs weekly

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/pkg-varnish-cache#137]
I was caught again by the fact that to build varnish-cache master, the weekly branch from this repository should be used.

Should we maybe
* keep master up to date to build master (as for weeklies)
* and branches tracking varnish-cache?

**Comment by Dridi** [comment]
The master branch is supposed to go away, and weekly should already be the default HEAD.

I think the reason why we kept master around was 4.1, so I think it's safe to kill now (and we have a 4.x branch anyway). Maybe 4.x needs to catch up with master before will remove it.

**Comment by gquintard** [comment]
Wouldn't it be easier to just say that `master` handles the weeklies, since they are produced from the `master` branch?

**Comment by gquintard** [comment]
@nigoroll , @Dridi ?

**Comment by nigoroll** [comment]
@gquintard again, my preference would be to use master for weeklies

**Comment by Dridi** [comment]
I couldn't care less.

**Comment by gquintard** [comment]
good, I merges `weeky` in to `master`, and I'll point https://github.com/varnishcache/varnish-cache/blob/master/.circleci/config.yml at `master` soon.
