### ISSUE TITLE
Add support for Ubuntu 20.04 'Focal Fossa'

### ISSUE THREAD

**Issue by geerlingguy** [varnishcache/pkg-varnish-cache#139]
It seems that Ubuntu 20.04's default apt repo includes a `varnish` package at 6.2.x, but the current version of Varnish is 6.4.x.

Packagecloud currently has packages for bionic and xenial, but not focal, so installation fails if you try using the PPA on Ubuntu: https://packagecloud.io/varnishcache/varnish64

Could we get support added for Ubuntu 20.04 Focal?

(Related: https://github.com/geerlingguy/ansible-role-varnish/issues/95).

**Comment by martin-g** [comment]
Hi,

There is an open PR at https://github.com/varnishcache/varnish-cache/pull/3263 that makes it very easy to add Ubuntu 20.04 to the list of OSes for which a package will be built!

I think it would be a good idea to replace Debian Bullseye with Ubuntu 20.04, because Bullseye is the new Debian _testing_.
@Dridi @gquintard Do you agree ?

**Comment by gquintard** [comment]
I don't see a reason to remove `bullseye`, quite the opposite actually, it will serve a "peek-into-the-future" platform and help us catch problems with newer libs/compilers.

It will be easy to add `focal` to the list and build packages from now own, but the current stance is to freeze the supported distribution on the release date. So adding `focal` support means packages for weeklies and the next release in September but not `6.4`

**Comment by 7php** [comment]
Hey @martin-g the PR for #https://github.com/varnishcache/varnish-cache/pull/3263 and #https://github.com/varnishcache/varnish-cache/pull/3313 have been closed.

If there any chance we see v6.4 for `focal` in the next few days? Or is it a dead-end till the next release as pointed out by @gquintard ?

**Comment by martin-g** [comment]
I'll let the Varnish team decide that!
I can send a new PR adding Focal as soon as the team approves it!

If approved the the .deb package will be a **nightly** build until an official release is made!

**Comment by 7php** [comment]
> I can send a new PR adding Focal as soon as the team approves it!
> 
> If approved the the .deb package will be a **nightly** build until the next official release is made!

Oh yes please if you can *waves*, thank you.

**Comment by martin-g** [comment]
https://github.com/varnishcache/varnish-cache/pull/3317

Varnish team will decide when/if to merge it!

**Comment by gquintard** [comment]
merged

**Comment by geerlingguy** [comment]
@gquintard - It looks like the focal build is available under [weeklies](https://packagecloud.io/varnishcache/varnish-weekly), but not under the 6.4 releases: https://packagecloud.io/varnishcache/varnish64. Is there any timeline for getting a stable release for 20.04?

**Comment by gquintard** [comment]
Hi,

No timeline, but we'll gladly review PRs for extra distribution support.

Note that we generally only consider new dist support only for weeklies and
LTS version, so 6.4 is not likely to support fossa.

-- 
Guillaume Quintard

**Comment by nicovs** [comment]
@gquintard you mean Focal is not LTS? https://releases.ubuntu.com/20.04/
Or am i missing something? :)

**Comment by gquintard** [comment]
@nicovs , I mean that 6.4 isn't an LTS, so it's not likely to see support for a new distribution (`focal` in this case)
