### ISSUE TITLE
6.6 packagecloud repo is empty

### ISSUE THREAD

**Issue by jerrac** [varnishcache/pkg-varnish-cache#147]
The 6.6 packagecloud repo is empty.

The one linked to from here: https://varnish-cache.org/releases/rel6.6.0.html#rel6-6-0

https://packagecloud.io/varnishcache/varnish66 givea me this: 
![image](https://user-images.githubusercontent.com/910764/111519715-9c852800-8714-11eb-9371-bb26b03ff86c.png)

**Comment by gquintard** [comment]
6.6 was released 2 days ago, we usually only start panicking after a week

**Comment by jerrac** [comment]
So it's normal for it to be empty for now?

I had not noticed it was a brand new release. I was just trying to test some stuff and wanted to use the latest version for testing. I've switched to 6.5 for now.

**Comment by gquintard** [comment]
it is normal :-) 6.6 is fresh out of the oven, and over the next week you'll get packages and docker images in the repos

**Comment by jerrac** [comment]
Ah ok.
