### ISSUE TITLE
Add support for Ubuntu 22.04 'Jammy Jellyfish' 

### ISSUE THREAD

**Issue by jmbiaudis** [varnishcache/pkg-varnish-cache#156]
Hello ,

It seems that Ubuntu 22.04's default apt repo Ubuntu main includes a varnish package at 6.6.x but other version including latest 7.1.x aren't available for this OS version.

Packagecloud currently has packages for focal, bionic and xenial, but not Jammy: 

-https://packagecloud.io/varnishcache/varnish60lts 
- Or https://packagecloud.io/varnishcache/varnish70 
- Or https://packagecloud.io/varnishcache/varnish71

Could we get support added for Ubuntu 22.04 'Jammy Jellyfish' ?

Thanks in advance .

Expected Behavior

Varnish 6.x lts or 7.1.x is installable on Jammy through packagecloud repo

Current Behavior

No support for Ubuntu 22.04 for the packagecloud repo (6.x lts , 7.x , 7.1.x )

Possible Solution

Support Varnish 6.x lts , 7.x  on Ubuntu 22.04 through packagecloud repo

Context

Your Environment

    Version used: Varnish 6.0.10-1~Focal LTS (packagecloud) or 6.6.1-1ubuntu0.2 (Ubuntu main)
    Operating System and version: Ubuntu 22.04
    Source of binary packages used (if any)

**Comment by Dridi** [comment]
Varnish 7.2.0 packages for Ubuntu 22.04 are available in packagecloud. For 6.0 LTS packages, we plan to have jammy packages for the next release, no ETA.

The 7.0 and 7.1 branches will not have jammy packages, and 7.0 reached its EOL.
