### ISSUE TITLE
Support for Debian 12

### ISSUE THREAD

**Issue by NielsH** [varnishcache/pkg-varnish-cache#167]
Hello,

Not sure if this is the correct place to report this.
We currently use the Packagecloud repo to install Varnish ( https://packagecloud.io/varnishcache/ ).

There are no Varnish packages for Debian 12. Are there any plans to add these (for Varnish 6.0/LTS)?
Thank you!

**Comment by NielsH** [comment]
Hi,

Thanks for adding it! If a release for Debian 12 could be made that would be great of course; I am not sure how other users do it but I would imagine that most people using Debian would want to use the official repository since it means there's no need to maintain their own repo, update it with new versions regularly, etc...

Currently this means we are stuck on Debian 11 until a new release is available on the repository :-(

**Comment by gquintard** [comment]
@Dridi , @hermunn , looks like this PR flew under the radar, can we take it in before the 7.4 packages are published?

**Comment by nigoroll** [comment]
It has been merged before the released was branched off. So I would think the only issue is that the 7.4 packages have not arrived yet.

**Comment by gquintard** [comment]
oh, right, I was checking the issue, not the PR, my bad @nigoroll , I'm closing this

**Comment by NielsH** [comment]
Hi all, thanks for your responses!

Just to clarify, we are using Varnish 6.0 (LTS) since Magento recommends using 6.x and 6.0 is the only non-EOL version: https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cache/varnish/config-varnish.html

**Comment by NielsH** [comment]
Hi all,

I see Varnish 6.0.12 has been released with a debian 12 package. Now we can finally upgrade our servers to Debian 12. thanks all! :+1:
