### ISSUE TITLE
systemd service file: Requires, After or Wants 

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#17]
In a pull-request to the old Varnish-Cache project github user @bmdan suggest that we change our systemd service files::

> "After" only ensures ordering if the targets are part of the same transaction. "Requires" only ensures that the targets are part of the same transaction, not ordering. Thus, both are necessary to ensure reliable and deterministic startup. Credit to @DavidStrauss at DrupalCon LA 2015 for spotting the issue! He also suggests dropping syslog.target, as it's deprecated. Quoth https://wiki.freedesktop.org/www/Software/systemd/syslog/:
> 
> "Newer systemd versions (v35+) do not support non-socket-activated syslog daemons anymore and we do no longer recommend people to order their units after syslog.target. That means that unless your syslog implementation is socket activatable many services will not be able to log to your syslog implementation and early boot messages are lost entirely to your implementation."

Suggested patch:
```
(=86628 vim:varnish.service) lkarsten@IMMER ~/work/pkg-varnish-cache/redhat> git df --cached
diff --git a/redhat/varnish.service b/redhat/varnish.service
index e8d442f..aec3f07 100644
--- a/redhat/varnish.service
+++ b/redhat/varnish.service
@@ -1,6 +1,6 @@
 [Unit]
 Description=Varnish Cache, a high-performance HTTP accelerator
-After=syslog.target network.target
+After=network.target
 
 [Service]
 # If you want to make changes to this file, please copy it to 
```

After discussing this a bit on IRC, there doesn't seem to be a consensus on how this should be done.

1) Should this be applied?
2) Should we add `Wants=network.target`?
3) Why is this not the same in the debian and redhat files?

Let's take the remaining discussion here, so we can complete the gitrepo move tasks.

**Comment by tfheen** [comment]
]] Lasse Karstensen 

> 1) Should this be applied?

No.  If you want it, use network-online.target.

> 2) Should we add Wants=network.target?

I don't think I've seen folks do that before.

> 3) Why is this not the same in the debian and redhat files?

No idea.  They should be moved closer together, IMO.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by fgsch** [comment]
I believe it's safe to remove the syslog.target though but I agree with Tollef about the rest.
