### ISSUE TITLE
-j option now allowed in debian distribution

### ISSUE THREAD

**Issue by DemonTPx** [varnishcache/pkg-varnish-cache#18]
Hi,

I've just installed varnish 4.1 on a ubuntu trusty server and noticed the following issue with the deb package.

I tried using the new jail argument `-j`. I should be able to
configure this in `/etc/default/varnish` in the `DAEMON_OPTS` variable. But
when I start the daemon, it fails with the following message:

     * Starting HTTP accelerator varnish
       ...fail!
    Error: -j must be the first argument

When I put the `-j` argument as the first argument in the `DAEMON_OPTS`, it
still fails. This is because in `/etc/init.d/varnish` `-P ${PIDFILE}` comes
before `${DAEMON_OPTS}`.

The only way to configure it is to edit `/etc/init.d/varnish`, but that doesn't seem like a good idea.

Cheers,
Bert

**Comment by fgsch** [comment]
Fix pushed. Next release should include it.
