### ISSUE TITLE
Systemd cannot reload varnish service, as TasksMax gets exceeded. 

### ISSUE THREAD

**Issue by bag-man** [varnishcache/pkg-varnish-cache#20]
I've mentioned on IRC that we are unable to run `systemctl reload varnish` as reload-vcl fails with ` reload-vcl[28101]: /usr/share/varnish/reload-vcl: 44: /usr/share/varnish/reload-vcl: Cannot fork`

@daghf Instructed me to add `TasksMax=infinity` to the unit file, and that then allowed reload-vcl to run successfully. He also suspected that "One could configure varnish with a min threads value that exceeds the default TasksMax"

I guess in some circumstances, the systemd slice can reach TasksMax and thus prevent reload-vcl from being forked. -xavierg. 

Hopefully this is useful to you, I can provide more information if you need it.

**Comment by fgsch** [comment]
Can you post the `systemctl status varnish` output please?

The equivalent to ulimit -u is LimitNPROC= so this might be a different issue. 

I suspect we might need both directives though

**Comment by fgsch** [comment]
Can you also let us know the distribution and version?

**Comment by bag-man** [comment]
Sorry I should have included that in the OP, we are running Ubuntu 16.04 in an LXC container.

		~> systemctl status varnish
		● varnish.service - Varnish Cache, a high-performance HTTP accelerator
			 Loaded: loaded (/lib/systemd/system/varnish.service; disabled; vendor preset: enabled)
			Drop-In: /etc/systemd/system/varnish.service.d
							 └─local.conf
			 Active: active (running) (Result: exit-code) since Thu 2016-04-07 15:41:46 UTC; 7min ago
			Process: 23348 ExecReload=/usr/share/varnish/reload-vcl (code=exited, status=2)
		 Main PID: 7032 (varnishd)
				Tasks: 512 (limit: 512)
			 Memory: 93.1M
					CPU: 2.387s
			 CGroup: /system.slice/varnish.service
							 ├─7032 /usr/sbin/varnishd -a :80 -a :6081,PROXY -f /etc/varnish/default.vcl -T 127.0.0.1:6082 -t 120 -p thread_pool_add_delay=2 -p th
							 └─7033 /usr/sbin/varnishd -a :80 -a :6081,PROXY -f /etc/varnish/default.vcl -T 127.0.0.1:6082 -t 120 -p thread_pool_add_delay=2 -p th

		Apr 07 15:42:12 nextgen3 systemd[1]: [/etc/systemd/system/varnish.service.d/local.conf:2] Maximum tasks value 'infinity # https://github.com/var
		Apr 07 15:42:13 nextgen3 systemd[1]: [/etc/systemd/system/varnish.service.d/local.conf:2] Maximum tasks value 'infinity # https://github.com/var
		Apr 07 15:46:00 nextgen3 systemd[1]: Reloading Varnish Cache, a high-performance HTTP accelerator.
		Apr 07 15:46:00 nextgen3 reload-vcl[14295]: /usr/share/varnish/reload-vcl: 44: /usr/share/varnish/reload-vcl: Cannot fork
		Apr 07 15:46:00 nextgen3 systemd[1]: varnish.service: Control process exited, code=exited status=2
		Apr 07 15:46:00 nextgen3 systemd[1]: Reload failed for Varnish Cache, a high-performance HTTP accelerator.
		Apr 07 15:49:26 nextgen3 systemd[1]: Reloading Varnish Cache, a high-performance HTTP accelerator.
		Apr 07 15:49:26 nextgen3 reload-vcl[23348]: /usr/share/varnish/reload-vcl: 44: /usr/share/varnish/reload-vcl: Cannot fork
		Apr 07 15:49:26 nextgen3 systemd[1]: varnish.service: Control process exited, code=exited status=2
		Apr 07 15:49:26 nextgen3 systemd[1]: Reload failed for Varnish Cache, a high-performance HTTP accelerator.

**Comment by fgsch** [comment]
Thanks for confirming it. Are you using the trusty package?

**Comment by fgsch** [comment]
This is related to the cgroup limits. 
More information here: https://www.kernel.org/doc/Documentation/cgroup-v1/pids.txt

We cannot add TasksMax blindly since it breaks in systemd < 228 unfortunately.

**Comment by lkarsten** [comment]
Trusting Federico's knowledge on versions, I looked up the different systemd versions.

Ubuntu Trusty runs upstart.
Ubuntu Xenial has 229.
Debian Jessie has 215.
Debian Stretch has 230.

Which means that we can add a pre-processor step in our packaging scripts to have this if we want to on recent platforms.

**Comment by lkarsten** [comment]
I'm closing this with a docfix for now.
