### ISSUE TITLE
Service do not start after upgrade 4 -> 4.1 Centos 6 

### ISSUE THREAD

**Issue by JoseGarciaRuiz** [varnishcache/pkg-varnish-cache#21]
File /etc/sysconfig/varnish is not updated after upgrade.
There are some incompatible params. User and group param do not work. Also listen address cannot be empty. Use * instead. Admin listen address cannot be 127.0.0.1 too, use * instead.

This fixes are not specified at 4.1 upgrade change log. Checking google is posible to find some other users experiencing the same problem. Some people just downgraded to 4.0. But 4.0 is not compatible with new VMODS

**Comment by lkarsten** [comment]
Hi.

`/etc/sysconfig/varnish` is marked as %config(noreplace) in the RPM configuration, and I believe that is the correct behaviour.

That file is where users normally set their extra varnishd arguments, we can't just overwrite it.

Upgrade documentation isn't exactly verbose, but it does mention that the new user settings.

With some luck people will find this github issue when they search in the future, and avoid spending the time you did on it! :)
