### ISSUE TITLE
PIDFILE incorrectly set when starting the service on system boot

### ISSUE THREAD

**Issue by Rylon** [varnishcache/pkg-varnish-cache#22]
Hi,

I have discovered another issue with the Debian init script PIDFILE generation, this time on system boot. Because the PIDFILE prefix is taken from `$SERVICE`, which is geneated like so:

`SERVICE="$(basename ${0})"`

When the system boots, `basename` returns the name of the startup symlink `S20varnish`, which means the resulting PIDFILE is incorrectly set as `/run/S20varnish.pid`.

This then causes the same problems described by my original bug report here https://github.com/varnishcache/varnish-cache/issues/1903.

I'm running Ubuntu 14.04 Trusty.

Thanks,
Ryan

**Comment by Rylon** [comment]
I believe this PR https://github.com/varnishcache/pkg-varnish-cache/issues/15 contains a fix for this by using `readlink` to retrieve the canonical filename.

**Comment by fgsch** [comment]
Personally I'd just go for varnishd. I doubt we're going to change the service name any time soon to justify the basename call.

**Comment by lkarsten** [comment]
Packages of 4.0.3-5 should appear on repo.v-c.o in a few minutes.

**Comment by Rylon** [comment]
Fantastic! Thanks everyone :D

**Comment by Rylon** [comment]
@lkarsten hi, just noticed the version you mentioned here was 4.0.3-5, will the PIDFILE fixes in this init script be brought forward into the 4.1 series too? The latest 4.1.2-2 package (for Trusty at lest) still contains the broken init script.

**Comment by MrJamesEllis** [comment]
I've got an issue with varnish (4.1) similar to the above comment on 14.04

When varnish first starts. e.g my dev box every morning, it's with these args:

```
/usr/sbin/varnishd -P /run/s20varnish.pid  etc etc
```

Trying to restart varnish (when it is running) leads to this error:

```
$ sudo service  varnish restart
 * Stopping HTTP accelerator varnish
No /usr/sbin/varnishd found running; none killed.  [fail]
 * Starting HTTP accelerator varnish [fail] 
Error: Cannot open socket: :80: Address already in use
```

At this point I guess it's because the restart script is looking for a PID file in  /run/varnish.pid

In order to restart varnish I have to kill the process:

```
sudo killall varnishd
```
.. and then restart, which it does:

```
$ sudo service varnish restart
 * Stopping HTTP accelerator varnish
No /usr/sbin/varnishd found running; none killed.  [fail]
 * Starting HTTP accelerator varnish [ OK ]
```

At this point varnishd is running with the following args:
```
/usr/sbin/varnishd -P /run/varnish.pid etc etc
```



Is this possibly because in /etc/init.d/varnish and in e.g /etc/rc5.d/s20varnish
```
SERVICE="$(basename ${0})"
```
which leads to SERVICE being "varnish" in the first case and "s20varnish" in the latter, leading to a discrepancy when you want to restart the running service ?


thanks!

**Comment by Preen** [comment]
+1

**Comment by fgsch** [comment]
4.1.3 beta packages are available at https://jenkins.varnish-software.com/view/VC4/job/VC4-deb/lastSuccessfulBuild/artifact/deb-build/
If you can give it a go and let us know if you find any issues.

**Comment by azeemism** [comment]
No .pid file seems to be created in Debian Jessie using v4.1.2-2~jessie
```
root@skynet:/run# ls -la /run | grep varnish
drwxr-xr-x  2 varnishlog     varnishlog   60 Jul  5 05:59 varnishlog
drwxr-xr-x  2 varnishlog     varnishlog   60 Jul  5 05:59 varnishncsa
```

```
cat /etc/systemd/system/varnish.service
[Unit]
Description=Varnish Cache, a high-performance HTTP accelerator

[Service]
Type=forking
LimitNOFILE=131072
LimitMEMLOCK=82000

ExecStart=/usr/sbin/varnishd \
        -a localhost:6018 \
        -T localhost:6082 \
        -f /etc/varnish/default.vcl \
        -S /etc/varnish/secret \
        -s malloc,4G

ExecReload=/usr/share/varnish/reload-vcl

[Install]
WantedBy=multi-user.target
```
Adding `-P /var/run/varnish.pid` result in varnish.pid owned by root
```
root@skynet:/run# ls -la | grep varnish
drwxr-xr-x  2 varnishlog     varnishlog   60 Jul  5 05:59 varnishlog
drwxr-xr-x  2 varnishlog     varnishlog   60 Jul  5 05:59 varnishncsa
-rw-r--r--  1 root           root          4 Jul  5 06:43 varnish.pid
```
If a varnish user and group are added then varnish fails to start. I assume .pid file ownership should be `varnish:varnish`?
```
root@skynet:/run# systemctl status -l varnish
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/etc/systemd/system/varnish.service; enabled)
   Active: failed (Result: exit-code) since Tue 2016-07-05 06:53:28 PDT; 1min 10s ago
  Process: 5720 ExecStart=/usr/sbin/varnishd -P /run/varnish.pid -a localhost:6018 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,4G -u varnish -g varnish (code=exited, status=1/FAILURE)
 Main PID: 5471 (code=exited, status=0/SUCCESS)

Jul 05 06:53:28 skynet varnishd[5720]: #   -s persistent (experimental)
Jul 05 06:53:28 skynet varnishd[5720]: -T address:port              # Telnet listen address and port
Jul 05 06:53:28 skynet varnishd[5720]: -t TTL                       # Default TTL
Jul 05 06:53:28 skynet varnishd[5720]: -V                           # version
Jul 05 06:53:28 skynet varnishd[5720]: -W waiter                    # Waiter implementation
Jul 05 06:53:28 skynet varnishd[5720]: #   -W epoll
Jul 05 06:53:28 skynet varnishd[5720]: #   -W poll
Jul 05 06:53:28 skynet systemd[1]: varnish.service: control process exited, code=exited status=1
Jul 05 06:53:28 skynet systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
Jul 05 06:53:28 skynet systemd[1]: Unit varnish.service entered failed state.
```

**Comment by fgsch** [comment]
@azeemism what problem are you experiencing? this issue is for the sysv init, not systemd.

**Comment by lkarsten** [comment]
Reading through this before packaging 4.1.3, my understanding of the ticket is that this is solved but was reopened just to keep it in our minds for 4.1. Fixed packages are in the 4.0 repo.

The latest comments seem to be about problems not related to pid files in sysv. Please open separate issues if you think these needs attention.

Closing.

**Comment by lkarsten** [comment]
4.1.3 packages are now out in the repositories which should finally fix this in both supported series.

**Comment by mikeybenson** [comment]
After updating from 4.0.3-2 to 4.0.3-5 I was getting the same PID issue. 

```
sudo service varnish restart ***
 * Stopping HTTP accelerator varnishd
 No /usr/sbin/varnishd found running; none killed.
```

Oddly  after I strung the commands together to kill varnishd and then restart varnish with the following:

`sudo killall varnishd && sudo service varnish restart`

I was able to run the restart command normally. I'm not sure if this is temporary but has been working on my dev box for several hours. Additionally there is the syntax message that hav'nt seen before.

```
sudo service varnish restart

 * Checking syntax varnishd    [ OK ] 
 * Stopping HTTP accelerator varnishd   [ OK ] 
 * Starting HTTP accelerator varnishd
```
Just throwing it out there in case it's helpful to someone.

**Comment by geerlingguy** [comment]
> 4.1.3 packages are now out in the repositories which should finally fix this in both supported series.

I seem to still be hitting this issue on Ubuntu 14.04. With Varnish 4.0.x (4.0.3 today) everything builds/runs normally ([example](https://travis-ci.org/geerlingguy/ansible-role-varnish/jobs/160608078)). With Varnish 4.1.x (4.1.3 today) Varnish gets stuck in a weird state where it starts but then isn't able to see that it's started, and I end up with the error when restarting Varnish:

```
/etc/init.d/varnish: 36: ulimit: error setting limit (Operation not permitted)
```

However, that error is a misdirection—the real issue is that varnishd is actually running. If I run `ps -ax` I get the following:

```
ps -ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /sbin/init
  960 ?        Ss     0:00 /usr/sbin/varnishd -a :80 -f /etc/varnish/default.vcl
  967 ?        Sl     0:00 /usr/sbin/varnishd -a :80 -f /etc/varnish/default.vcl
```

Note that no other platform seems to run into this issue (I'm testing CentOS 6/7, Ubuntu 16.04/14.04, and Debian 8: https://travis-ci.org/geerlingguy/ansible-role-varnish/builds/160608074).

**Comment by geerlingguy** [comment]
Note: This also happens with 5.0.0 on Ubuntu 14.04—and none of the other OSes I've tested it with. See builds: https://travis-ci.org/geerlingguy/ansible-role-varnish/builds/160610850

**Comment by eucm2** [comment]
you need to stop apache
service apache2 stop
After you can star varnish
service varnish star

So you need changue apache port configuration. Go to "/etc/apache2/ports.conf" and change
Listen 80
for this
Listen 8080
