### ISSUE TITLE
Debian systemd service doesn't use EnvironmentFile

### ISSUE THREAD

**Issue by stephenreay** [varnishcache/pkg-varnish-cache#24]
I'm curious why the service files for rpm vs deb packages are so different? The one for RedHat/etc has a dedicated params file placed in /etc, whereas with the .deb it's all hard-coded in the .service file.

**Comment by fgsch** [comment]
The recommended way to do this in Debian / Ubuntu is using drop-in files. 
See systemd.unit.

**Comment by stephenreay** [comment]
You mean e.g. creating /etc/systemd/system/varnish.service.d/local.conf with a replacement (well 2: 1 to clear and one to assign) ExecStart line?

That does seem to work, so thanks for the heads up. Is the use of EnvironmentFile's specifically discouraged by Debian policy?

**Comment by fgsch** [comment]
Yup, that's what I meant and my my understanding.  See https://github.com/varnish/Varnish-Cache/pull/92. 
@ssm and @tfheen might have some input here.

**Comment by tfheen** [comment]
> That does seem to work, so thanks for the heads up. Is the use of
> EnvironmentFile's specifically discouraged by Debian policy?

It's generally discouraged by systemd upstream.

**Comment by denisbr** [comment]
Any references to that @tfheen? I'd like to understand the rationale.

**Comment by tfheen** [comment]
It's mentioned in https://github.com/systemd/systemd/issues/1082#issuecomment-136452207 at least.

Lennart writes:

> To make this clear: we think that unit files and the daemon's own configuration files are where configuration should be placed, and not in split-out environment files. That's just making things worse, by adding another configuration file. Now, while it's OK if people do things like this anyway, even though we think it's not how daemons should work these days, but if you want to do that, you actually are looking for a proper shell, and that's what you should be using then. We explicitly do not want to turn systemd's unit files into yet another shell engine.

**Comment by stephenreay** [comment]
Thanks for the reference, I'm not quite sure I agree with Lennart's point though.

My initial goal in this instance, was to change the bind port from `:6081` to `0.0.0.0:80` - to achieve this I have to re-create the entire ExecStart line.

However, to get back to the original question: - if it's a SystemD "recommendation", why is the RPM ignoring that and using the EnvironmentFile? And to dig deeper, why, if the whole point of systemd is to *end* the distro-specific init scripts, are there separate service files for each one?

**Comment by fgsch** [comment]
@ingvarha might know.

**Comment by denisbr** [comment]
Thanks for the reference @tfheen The official documentation for things doesn't reflect this at all (yet), that's why it came as a bit of a surprise to me.
Would it help if the explanation for how to change the startup parameters was part of the shipped service files (comments?), so that people not yet familiar with the systemd way of doing things didn't have to search for an explanation? I know I would have appreciated that at least.

**Comment by stephenreay** [comment]
A comment indicating how to make changes (i.e. "Don't edit this file directly, instead do X" in the service file) would definitely be an improvement - but I would still definitely be in favour of ~~the EnvironmentFile~~ some simple override approach being supported.

As I was checking how other packages for Debian do this (e.g. SSH and cron use EnvironmentFile) I came across a suggestion that you can use Env Vars in ExecStart, but put the values into a SystemD file still. This still means you use an `/etc/systemd/system/varnish.service.d/*.conf` file to override the defaults, but it also simplifies small changes to something like:

    [Service]
    Environment="VARNISH_MEMORY=384m"

This also doesn't stop someone using the drop-in file to do more advanced changes (i.e. adding a second listening port with `,PROXY`) by overriding the ExecStart line.

The linked systemd service file in the Hitch wiki (https://gist.github.com/lkarsten/59e0827ead63e41cf760) uses this method in combination with multiple EnvironmentFile lines. I wouldn't bother going that far, but IMO it's still a better choice than needing to supply a full ExecStart line.

**Comment by fgsch** [comment]
This is somewhat documented at https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html but could be improved.

Not sure if it makes sense to duplicate the info on the service file itself.

The environment approach has some issues, e.g. how the shell does the parsing, escaping, handles empty parameters. There are some things that AFAICT won't work with this approach, e.g. -S "".

**Comment by stephenreay** [comment]
Re: the comment - maybe just a single "Don't edit this file, see <URL>"  or something?

The way systemd handles parameters like this definitely isn't ideal, but I've tested a couple of local changes and the *only* situation I can't make work right now, is when you e.g. want to specify a path with spaces (that would normally be quoted) to -S. I *know* there will always be some situation that *requires* the operator to write their own ExecStart line - all i'm suggesting is simplifying the situation for the vast majority of installs where it's more likely they just want to make a simple change to one of the default parameters.

Digging into variable substitution, it's certainly not as predictable as with a real shell:

The systemd docs indicate that `${VAR_NAME}` will be treated as a single argument with space intact, but varnishd treats it as multiple arguments. I haven't got to the point of trying the same approach with something else to see if it's the way systemd populates arguments or the way varnish handles arguments.

However, to satisfy the example you gave (setting an empty param) i found just `VARNISH_SECRET=` in the drop-in file and `-S ${VARNISH_SECRET}` in the main .service file worked as expected (i see 'Warning: Empty -S argument, no CLI authentication' in the output from `service varnish status`

**Comment by fgsch** [comment]
Are you using EnvironmentFile? If that's the case it doesn't seem to be working here but I might be missing something.

Anyway, unless there is an agreement with the different distributions we officially support, I cannot really see an advantage by having different set of service files.  It will only confuse the end user and make maintenance a nightmare.

Furthermore, the `ExecStart` has been quite simplified from the sysv one. Copying the existing line, i.e. `/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m` to a new file and tweak it shouldn't be an issue IMO.

**Comment by fgsch** [comment]
Something else that should be pointed out. In the future the packaging might be only done downstream.

If you are really adamant about this it might be worth taking it to the respective maintainers.

**Comment by stephenreay** [comment]
OK, so it actually *does* work with files with spaces. I was just not paying enough attention to the error varnish was giving (i was touching the file to use for the secret, but it had no contents, so it was exiting)

Anyway, it works without the use of EnvironmentFile, for both arguments with a space and "empty" arguments - see https://gist.github.com/stephenreay/f3e7a9373fad89d513d7743f5fc509b7

I agree that a single service file regardless of distro makes the most sense - hence the original question was "why is it different in rpm vs deb".

Ultimately, this is just a convenience thing - I can obviously still use the Env method in a unit file with it's own modified ExecStart - the only reason I asked is because the two service files take such a different approach - and the 'official' debian one is different again, because it runs in a jail in foreground mode.

As I understand it @ssm is one of the maintainers for the official Debian package, and his suggestion on the 'original' issue about this was to just overwrite the ExecStart line. If that's the recommended method for Debian, I'd prefer this package follow their standard than going the opposite direction, it just seems a little un-Debian like after many years of the relatively simple /etc/default/* system with sysvinit.

**Comment by fgsch** [comment]
I still cannot get the empty arguments to work on my tests here but regardless, this is the official way, at least in the deb world. 

The rpm scripts were done by @ingvarha AFAIK. There might be a reason why they are different, idk.   It'd be nice to reduce differences and we might look into it in the future.

We have no plans to divert from downstream, however. Sorry. I'm closing this ticket.
