### ISSUE TITLE
systemd varnish.unit not using /etc/default/varnish

### ISSUE THREAD

**Issue by fgsch** [varnishcache/pkg-varnish-cache#25]
## Expected Behavior
When using systemd, editing /etc/default/varnish and restarting varnish, changement must be applied.

## Current Behavior
When starting varnish only the default configuration present in /lib/systemd/system/varnish.service is used.

## Possible Solution
We could use the next code for the systemd unit.
Explanation : 
- whe define default value and 
- if value are present in /etc/default/varnish, they overide defaults values.
- ExecStartPre will check vcl syntax

```
[Unit]
Description=Varnish HTTP accelerator

[Service]
Type=forking
LimitNOFILE=131072
LimitMEMLOCK=82000
Environment="DAEMON_OPTS=-a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m"
EnvironmentFile=-/etc/default/varnish
ExecStartPre=/usr/sbin/varnishd -C -f /etc/varnish/default.vcl
ExecStart=/usr/sbin/varnishd $DAEMON_OPTS
ExecReload=/usr/share/varnish/reload-vcl

[Install]
WantedBy=multi-user.target
```

## Steps to Reproduce (for bugs)
1. edit /etc/default/varnish to listen on a new port
2. /etc/init.d/varnish restart (or systemd syntax)
3. netstat -lpne | grep varnish #varnish always listen on

## Environment
* Version used:varnish  4.1.2-2~jessie amd64
* Operating System and version: debian 8(jessie)
* systemd package present on the system (fresh install)

**Comment by fgsch** [comment]
Moved from https://github.com/varnishcache/varnish-cache/issues/1929

**Comment by fgsch** [comment]
service services are managed in a different way. 

The confusion might arise since Jessie was not a pure systemd distribution IIRC (systemd was added post release) so we're still shipping the old sysv configuration file.

In the future this might not be the case. For systemd please see https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html.

**Comment by rapind** [comment]
Is this still working? Followed instructions @ https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html but no dice.

**Comment by TipiT** [comment]
Depends which OS and release you use. Some systems from us use Ubuntu 16.04 so it needs to be done through systemd.

Quickly explained:
1. mkdir -p /etc/systemd/system/varnish.service.d/
2. Create a file override.conf where you include the overrides.
E.g.
`[Service]
ExecStart=
ExecStart=/usr/sbin/varnishd -a :8000 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,512M`
3. systemctl daemon-reload
4. systemctl restart varnish

Here is also a great answer about this: http://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services
