### ISSUE TITLE
Verify PCRE jit status

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#3]
```
[13:17:44] < fgs> re #1630 I suspect we have a packaging building issue
[13:18:14] < fgs> and jit was not enabled
[13:18:17] < fgs> on 4.1
[13:20:06] < scn> #1630
[13:20:07] -beb:#varnish-hacking- #1630: Varnish crashes with long regex condition [closed] 
          https://www.varnish-cache.org/trac/ticket/1630
[13:21:26] < fgs> if the logs are correct we have pcre 8.31 installed
[13:21:44] < fgs> jit is enabled on > 8.31
[13:23:35] < scn> i'll put it on my list of things to check before 4.1.1
```

**Comment by fgsch** [comment]
FWIW, I've changed configure.ac in master to output whether pcre jit is available during configure time.
This will give us somewhat more insight.

**Comment by lkarsten** [comment]
From https://jenkins.varnish-software.com/view/VC-4.1/job/varnish-4.1-src/29/consoleFull :
```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PCRE... yes
checking for PCRE JIT usability... no
```

```
root@blaam:/# schroot --chroot varnish
(varnish)root@blaam:/# dpkg -l | grep pcre
ii  libpcre3                        8.12-4                     Perl 5 Compatible Regular Expression Library - runtime files
ii  libpcre3-dev                    8.12-4                     Perl 5 Compatible Regular Expression Library - development files
ii  libpcrecpp0                     8.12-4                     Perl 5 Compatible Regular Expression Library - C++ runtime files
(varnish)root@blaam:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
(varnish)root@blaam:/#
```

If we want this, I guess our easiest way is to build 8.31 (?) onto precise, or upgrade the "varnish" chroot to trusty. If we can find the time for it, I think getting off precise would be worth the effort. @fgsch ?

**Comment by fgsch** [comment]
@lkarsten we'll need to build against 8.32 and package it as well to distribute it.
Do we really want to go down that road?

**Comment by lkarsten** [comment]
I'm mixing this up. My understanding was that we needed it working in the -src job to enable it later on, but it is of course not the case.

Searching for "checking for PCRE JIT" on: 
https://jenkins.varnish-software.com/view/VC-4.1/job/varnish-4.1-deb-debian-wheezy-amd64/52/consoleFull
shows that configure finds it in the jessie chroot just fine. (not the others, assuming they are too old)

Summing up it should work fine on Linux distros with sufficiently new libpcre. I don't see us doing anything else here?
