### ISSUE TITLE
"systemctl varnishncsa reload" stops varnishncsa on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mwpastore** [varnishcache/pkg-varnish-cache#31]
Reloading the varnishncsa service on Ubuntu 16.04 LTS stops the varnishncsa daemon. This is particularly an issue because the `postrotate` script in `/etc/logrotate.d/varnish` calls `/usr/sbin/invoke-rc.d varnishncsa reload`. To wit:

```
# systemctl is-active varnishncsa
inactive
# systemctl start varnishncsa
# systemctl is-active varnishncsa
active
# systemctl reload varnishncsa
# systemctl is-active varnishncsa
inactive
```

I'm using [the varnish package that comes with 16.04](http://packages.ubuntu.com/xenial/web/varnish) because the "official" repository is not yet available for Xenial. I can confirm that the typo described in #28 is not present (i.e. the fix is applied).

Possibly related to/regression of/duplicate of:
- #28 
- #27 
- #30 
- varnishcache/varnish-cache#1850
- varnishcache/varnish-cache#1756

**Comment by fgsch** [comment]
What's the output of `systemctl status -l varnishncsa` after the reload?

**Comment by mwpastore** [comment]
```
# systemctl status -l varnishncsa
● varnishncsa.service - Varnish HTTP accelerator log daemon
   Loaded: loaded (/lib/systemd/system/varnishncsa.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sat 2016-06-04 16:03:09 UTC; 5s ago
  Process: 1186 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 1144 ExecStart=/usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log (code=exited, status=0/SUCCESS)
 Main PID: 1144 (code=exited, status=0/SUCCESS)

Jun 04 16:02:58 atl-web-001 systemd[1]: Started Varnish HTTP accelerator log daemon.
Jun 04 16:03:09 atl-web-001 systemd[1]: Reloading Varnish HTTP accelerator log daemon.
Jun 04 16:03:09 atl-web-001 systemd[1]: Reloaded Varnish HTTP accelerator log daemon.
```

**Comment by fgsch** [comment]
Thanks. -D is missing. 
Which version of varnish is this?

**Comment by mwpastore** [comment]
It's the version that comes with Ubuntu 16.04 LTS:

```
$ dpkg-query -W varnish
varnish	4.1.1-1
```

**Comment by fgsch** [comment]
This should be fixed in 4.1.2. 
Can you give it a try and let us know?

**Comment by mwpastore** [comment]
To the best of my knowledge, a 4.1.2 package isn't available for Xenial. The [repo URL](https://repo.varnish-cache.org/ubuntu/dists/xenial) returns a 404.

**Comment by fgsch** [comment]
We don't have any xenial packages at all but I can see downstream does not have a 4.1.2 package.
I'd suggest you to ping downstream to get the package in xenial updated.
CC @ssm.

**Comment by ssm** [comment]
I've packaged 4.1.2 for Debian. Ubuntu will normaly pick packages from Debian unstable automatically for their new releases.  

For existing releases, like "xenial", the version will stay the same, but fixes may be backported from newer to older releases.  

Ubuntu also has "point releases", according to https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule there should be one in July.  I _think_ a new Varnish version can be included then, but I've no idea on which process they use. https://bugs.launchpad.net/ubuntu/+source/varnish is most likely the starting point for getting a newer Varnish package in.

**Comment by mwpastore** [comment]
Is there a plan to make packages available for Xenial at repo.varnish-cache.org at some point in the future?

**Comment by fgsch** [comment]
@lkarsten , this is for you.

**Comment by lkarsten** [comment]
For this specific issue, I would prefer if we could get Ubuntu to repackage with a new `varnishncsa.service` file that isn't broken. Anyone know how we get in touch with them?

**Comment by ssm** [comment]
https://launchpad.net/ubuntu/xenial/+source/varnish is the place for that, unless the change also makes sense for Debian.

**Comment by lkarsten** [comment]
There is an open issue on this with ubuntu already: https://bugs.launchpad.net/ubuntu/+source/varnish/+bug/1597911

Best case is if we could get this flagged as important there somehow.


In Debian I believe this was fixed by 784290d in pkg-varnish.git: https://anonscm.debian.org/cgit/pkg-varnish/pkg-varnish.git/commit/?id=784290d6e070eb9c9271fea39f71466e878769c9

**Comment by madpsy** [comment]
Adding '-D' for varnishncsa appears to cause systemd to think the process existed (presumibly because it forks a new process). 

```
● varnishncsa.service - Varnish HTTP accelerator log daemon
   Loaded: loaded (/lib/systemd/system/varnishncsa.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2016-09-07 09:56:19 UTC; 4s ago
  Process: 18424 ExecStart=/usr/bin/varnishncsa -D -a -w /var/log/varnish/varnishncsa.log (code=exited, status=0/SUCCESS
 Main PID: 18424 (code=exited, status=0/SUCCESS)
```

However, without '-D' it works as far as the process running is concerned (but of course breaks on 'reload').

Am I missing something obvious here or is '-D' actually not the fix?

Thanks

**Comment by madpsy** [comment]
So possibly my ignorance here, there's more to it than just adding '-D'. These service definitions work for me:

``
[Service]
RuntimeDirectory=varnishlog
Type=forking
User=varnishlog
Group=varnish
ExecStart=/usr/bin/varnishlog -D -a -w /var/log/varnish/varnish.log -P /run/varnishlog/varnishlog.pid
ExecReload=/bin/kill -HUP $MAINPID
PrivateDevices=true
PrivateNetwork=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
PIDFile=/run/varnishlog/varnishlog.pid
``

``
[Service]
RuntimeDirectory=varnishncsa
Type=forking
User=varnishlog
Group=varnish
ExecStart=/usr/bin/varnishncsa -D -a -w /var/log/varnish/varnishncsa.log -P /run/varnishlog/varnishncsa.pid
ExecReload=/bin/kill -HUP $MAINPID
PrivateDevices=true
PrivateNetwork=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
PIDFile=/run/varnishlog/varnishncsa.pid
``

**Comment by shankerbalan** [comment]
Thanks @madpsy, your configs are working well for me.

**Comment by denisbr** [comment]
I'm closing this ticket. Status is:

* The up to date service files in this repo work well with reloading.
* An official 4.1.x package for ubuntu xenial is currently available in the repo : 
https://packagecloud.io/varnishcache/varnish41
