### ISSUE TITLE
Ubuntu 16.04.1 LTS (Xenial Xerus) was released back in april

### ISSUE THREAD

**Issue by fgsch** [varnishcache/pkg-varnish-cache#36]
Moved from https://github.com/varnishcache/varnish-cache/issues/2037.  CC @bjornbak.

Please create an apt repository for xenial as it is the latest LTS release for Ubuntu.

**Comment by lkarsten** [comment]
Coming up towards 5.0 and H2, having openssl 1.0.2 is becoming a factor.

**Comment by craigcarnell** [comment]
@lkarsten Would appreciate this being fixed. Installing the trusty release in xenial has the following issue

```
W: https://repo.varnish-cache.org/ubuntu/dists/trusty/InRelease: Signature by key xx uses weak digest algorithm (SHA1)
```

**Comment by craigcarnell** [comment]
@lkarsten This is not about a new release, this is about fixing the gpg key on the server itself.

**Comment by luisdavim** [comment]
Any plans to add xenial packages to https://repo.varnish-cache.org/ubuntu/ ?

**Comment by lkarsten** [comment]
Current plan is to support it for Varnish Cache 5.0. No immediate plans for 4.1 builds.

**Comment by lkarsten** [comment]
Packages that should work on xenial are here: https://repo.varnish-cache.org/pkg/5.0.0/

Closing this issue now, please open another issue if you run into any problems with them.
