### ISSUE TITLE
varnish-modules packages for ubuntu

### ISSUE THREAD

**Issue by luisdavim** [varnishcache/pkg-varnish-cache#41]
It would be grate to have packages for varnish-modules in https://repo.varnish-cache.org/ubuntu/

**Comment by denisbr** [comment]
Sorry for not replying to this. At the moment building varnish-modules is out of scope for the packaging effort in the project. I'll close the ticket for now.

**Comment by ebpitts** [comment]
Is there a chance that build varnish-modules packages will be considered in-scope now or in the future?

**Comment by denisbr** [comment]
@ebpitts At the moment, this is not under consideration. Building varnish modules on 4.x and later is not as hard as it used to be on Varnish 3.x. Also in the project we have a need for focus on the core components, and limiting supported items is important.

**Comment by Dridi** [comment]
Also worth mentioning: varnish-modules is not under the @varnishcache organization, so it feels wrong to package a "foreign" project here.
