### ISSUE TITLE
VCL labels may not contain ":" anymore

### ISSUE THREAD

**Issue by simonvik** [varnishcache/pkg-varnish-cache#42]
It seems like the following commit removed the support for having ":" in VCL-names.

https://github.com/varnishcache/varnish-cache/commit/169e162c7506614090a33faef7a0df38c6ffac7a

This causes reload-vcl to fail when building against trunk.

**Comment by lkarsten** [comment]
Thanks for reporting. Will you consider cooking up a patch for it?

**Comment by simonvik** [comment]
Seems to be the same problem in the redhat one but i have no way of testing that here.

**Comment by lkarsten** [comment]
Remaining: Fix on RPM side.

**Comment by ingvarha** [comment]
Red Hat fix, please pull
https://github.com/varnishcache/pkg-varnish-cache/pull/63

**Comment by denisbr** [comment]
As both debian and redhat were fixed, and the fixes included in the most recent releases I am closing this.
