### ISSUE TITLE
Varnish 5.0 packaging?

### ISSUE THREAD

**Issue by geerlingguy** [varnishcache/pkg-varnish-cache#45]
While readying my Ansible role for Varnish for 5.x (https://github.com/geerlingguy/ansible-role-varnish/issues/39), I noticed that the 5.0 packages aren't built yet—is this the right place to stick an issue tracking 5.0 package build progress?

**Comment by lkarsten** [comment]
Packages are here: https://repo.varnish-cache.org/pkg/5.0.0/

**Comment by geerlingguy** [comment]
@lkarsten - Ah, never thought to look there. Will all the platform packages be built in a version-per-directory moving forward (e.g. 5.1, 5.2, etc.)? I just ask because each time there's a change like this, I need to change my Ansible role to make it easier for users to just specify a version instead of having to specify the entire RPM/deb URL...

**Comment by geerlingguy** [comment]
I'm trying to figure out the best way to make this a parameterized RPM URL, something like:

```
https://repo.varnish-cache.org/pkg/{{ varnish_version }}/varnish-{{ varnish_version }}-1.el{{ ansible_distribution_version.split(".")[0] }}.{{ ansible_architecture }}.rpm
```

Currently this would allow me to set a version like `5.0.0`. But there's the additional `-1` in the .rpm filename itself, which I'm guessing could increment along with the version...

I guess the point I'm trying to make is that switching the repo layout like this is a bit of a burden for anyone who wants to automate the install of Varnish—especially across platforms and additionally across platform versions :/

**Comment by geerlingguy** [comment]
I guess the main question I have is—will there be official packages available in a yum/apt repo for 5.x like there were for 3.x/4.x? (e.g. https://www.varnish-cache.org/releases/install_redhat.html and https://www.varnish-cache.org/releases/install_debian.html#install-debian)

**Comment by lkarsten** [comment]
Hi all. This is a good question, that currently doesn't have an answer. We'll know more in a couple of weeks.

If anyone volunteers to keep such a repo running, either through some of the hosted services or running repo software on the behalf of the Varnish project, I think that would be the best solution.

**Comment by lkarsten** [comment]
that being said, your specific problem here could be solved by just making some varnish-latest.deb symlinks. Maybe that is what we need? Is running a repo still as important as it was 10 years ago, or have the whole ansible/docker/containerization movement made it less of a requirement?

**Comment by ingvarha** [comment]
This is quite unofficial, but may grow into more official over time. Testing and feedback is very welcome. The repos should be compatible with epel5, epel6, and epel7.

https://copr.fedorainfracloud.org/coprs/ingvar/varnish50/

Ingvar

**Comment by fgsch** [comment]
@lkarsten I'm more or less happy to take this forward for the deb packages at least, partially because I want to make my life easier wrt testing and travis-ci.

**Comment by craigcarnell** [comment]
What about updating your ubuntu repo (e.g. xenial) with 5.0.0? I will have to change my puppet configs to install: https://repo.varnish-cache.org/pkg/5.0.0/varnish_5.0.0-1_amd64.deb

Is that correct?

**Comment by carlwgeorge** [comment]
> If anyone volunteers to keep such a repo running, either through some of the hosted services or running repo software on the behalf of the Varnish project, I think that would be the best solution.

@lkarsten Is it fair to interpret this statement as the Varnish project losing interest in maintaining packages themselves?  That's fine if that's the case, I'm just curious.  I'm specifically interested because I'm involved with the [IUS project](https://ius.io), and we received a [request to create varnish50u RPMs](https://github.com/iuscommunity/wishlist/issues/98).  If new varnish RPMs are imminent in your repo, it won't make much sense for IUS to build them, but if you no longer with to maintain a repository then adding it to IUS would be more appealing.

**Comment by ingvarha** [comment]
This boils down to who "owns" the varnish-cache.org site, and the repos there. I may volunteer to maintain the Red Hat & clones repo. The packages would be based on the pkg-varnish-cache repo and the epel packages. @lkarsten, would you be interested in this?

**Comment by denisbr** [comment]
I have been tasked with taking over the packaging effort from @lkarsten 
Our aim is to keep packaging stable Varnish Cache going forward, and most likely find a way to keep the packages hosted in a set of repositories like before. Collaboration with @ingvarha and @ssm on their efforts is of course important, as it has always been. 

@carlwgeorge the short answer is no, there is interest, and resources, in the project to keep maintaining stable packaging. As you might know, the project has been through a transition on a few areas. 

@craigcarnell we're working on how to continue the repository-effort, I cannot promise any concrete date here and now for when Xenial 5.0.x packages will be available from a repository, so for now, please take appropriate measures on your end.

**Comment by craigcarnell** [comment]
@denisbr Any updates on this?

**Comment by denisbr** [comment]
@craigcarnell Yesterday the Varnish Cache project released Varnish Cache 5.1, and as part of this, updated packages are now available through the projects [packagecloud.io/varnishcache/varnish5](https://packagecloud.io/varnishcache/varnish5) repository. 

These official repositories will get new versions whenever the Varnish Cache project releases new, rubberstamped, versions.

**Comment by joshuaspence** [comment]
Great work @denisbr.

**Comment by craigcarnell** [comment]
@denisbr Thank you. 

But for some reason, I get the following error:

```
Reading package lists... Done
W: The repository 'https://packagecloud.io/varnishcache/varnish51/ubuntu trusty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

content of /etc/apt/sources.list.d/varnishcache_varnish51.list
```
deb https://packagecloud.io/varnishcache/varnish51/ubuntu/ xenial main
```

**Comment by denisbr** [comment]
@craigcarnell Sorry about not getting back to you. 
The repo is actually https://packagecloud.io/varnishcache/varnish5, which collects any release in 5.x. After some discussions, we're going to add separate repos for 5.0 and 5.1 too, which limits packages to the same sub-revision.

**Comment by denisbr** [comment]
@craigcarnell I've created the additional repositories, and populated them with the relevant releases.

Specific version releases:
https://packagecloud.io/varnishcache/varnish51
https://packagecloud.io/varnishcache/varnish50
Any 5.x release:
https://packagecloud.io/varnishcache/varnish5

I'm closing this issue.

**Comment by aayllon** [comment]
@denisbr I'm tying to use the new repos,

https://packagecloud.io/varnishcache/varnish51
https://packagecloud.io/varnishcache/varnish50
https://packagecloud.io/varnishcache/varnish5

Here are the content from my /etc/apt/sources.list.d/varnishcache_varnish51.list file;

```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/varnishcache/varnish51

deb https://packagecloud.io/varnishcache/varnish5/ubuntu/ xenial main
deb-src https://packagecloud.io/varnishcache/varnish5/ubuntu/ xenial main
```
But when I make an apt-get update always get the same error;

```Err:3 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main Sources
  Received HTTP code 403 from proxy after CONNECT

Reading package lists... Done
W: The repository 'https://packagecloud.io/varnishcache/varnish5/ubuntu xenial Release' does not have a Release file.
```

Please could you help me to install varnish 5 or 5.1 from teh repos?

Thanks

**Comment by denisbr** [comment]
@aayllon This works for me. This issuetracker is not for support purposes, but for package related bugs.

**Comment by ediazcomellas** [comment]
There are no packages compiled for ubuntu/bionic in the 5.x release. I know they are fairly old, but they are still useful, as Magento still doesn't suports the 6.x branch.  I'm able to use the xenial packages, but would be nice to have them available also for bionic. 

Thanks very much.

**Comment by espebra** [comment]
5.x is not a long term support release and is EOL. For this reason it will not receive updates, and not be packaged for newer distribution releases.

That said, 6.x is very close to 5.x and I would be surprised if Magento does not work out of the box with 6.x if it works with 5.x.

**Comment by Dridi** [comment]
Hello @ediazcomellas,

Unfortunately this is definitely not happening on our end. All 5.x releases are retired and will see no further support, and they had close to none in the first place. You have a couple options if you wish to install Varnish as a package on bionic and work with Magento:

* clone this repository, use the 6.x branch's scripts to build bionic debs with a 5.x release.
* https://www.varnish-software.com/wiki/content/tutorials/magento2/m2_step_by_step.html
* https://info.varnish-software.com/blog/boost-e-commerce-site-performance

**Comment by ediazcomellas** [comment]
> 5.x is not a long term support release and is EOL. For this reason it will not receive updates, and not be packaged for newer distribution releases.
> 
> That said, 6.x is very close to 5.x and I would be surprised if Magento does not work out of the box with 6.x if it works with 5.x.

I understand. That being said, xenial packages install without problem in bionic. If you could just link the directory it would solve automated install issues. 

Thanks again.
