### ISSUE TITLE
Varnish 5 on Ubuntu `LIBVARNISHAPI_1.5' not found after upgrade from version 4

### ISSUE THREAD

**Issue by guycalledseven** [varnishcache/pkg-varnish-cache#47]
I upgraded to varnish_5.0.0-1_amd64.deb from https://repo.varnish-cache.org/pkg/5.0.0/ on Ubuntu 16.04.1 LTS  which was previously running official xenial varnish 4.1.1-1 and I was only able to run varnishd and varnishtest.

I removed varnish 4.1.1-1 with apt-get remove --purge but libvarnishapi1 stayed causing errors.
apt remove libvarnishapi solved that, but why did it stay on system in first place? 

```
dpkg-query -W varnish
varnish 5.0.0-1
```

```
varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

Other binaries complain about missing **LIBVARNISHAPI_1.5**.

```
varnishadm: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishadm)
varnishtop: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishtop)
varnishstat: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishstat)
varnishncsa: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishncsa)
varnishlog: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishlog)
varnishhist: /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1: version `LIBVARNISHAPI_1.5' not found (required by varnishhist)
```

edit: versions

**Comment by paliarush** [comment]
Encountered the same error, when in parallel with Varnish 5 had Varnish 3 installed on Ubuntu (using apt-get install). The following helped to make varnish 5 work:

```
sudo apt-get remove varnish
sudo apt-get remove --auto-remove varnish
sudo apt-get purge varnish
sudo apt-get purge --auto-remove varnish
```

**Comment by acachy** [comment]
Manual solution 

By "find / -name libvarnishapi.so.1" you will see something like 
/usr/lib/libvarnishapi.so.1
/usr/lib/x86_64-linux-gnu/libvarnishapi.so.1

Where /usr/lib/libvarnishapi.so.1 - is link to an actual version of library (at least if you use common configure option --localstatedir=/var/lib). 
And /usr/lib/x86_64-linux-gnu/libvarnishapi.so.1 is the old link.

More info 
ldconfig -v | grep varnish
        libvarnishapi.so.1 -> libvarnishapi.so.1.0.0
        libvarnishapi.so.1 -> libvarnishapi.so.1.0.6

Old link have some priority. 

- just clean old versions:
 rm /usr/lib/x86_64-linux-gnu/libvarnishapi.*
- rebuild links and check for sure:
 ldconfig && ldconfig -v | grep varnish

**Comment by denisbr** [comment]
This issue is caused by the changed structure in the project packaging.
If you add the new repository (https://packagecloud.io/varnishcache/varnish5) you should be able to perform upgrades from any varnish 4.1.x package like this:

```
$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  libvarnishapi1
The following packages will be upgraded:
  varnish
1 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Need to get 2,305 kB of archives.
After this operation, 8,497 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

This works without any manual fiddling. I would definitely not recommend the approach taken by @acachy
