### ISSUE TITLE
Ubuntu/Debian package overwrites systemd service

### ISSUE THREAD

**Issue by Napsty** [varnishcache/pkg-varnish-cache#48]
Varnish version: 4.1.x
OS: Ubuntu 16.04 x86_84 

	DISTRIB_ID=Ubuntu
	DISTRIB_RELEASE=16.04
	DISTRIB_CODENAME=xenial
	DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
	NAME="Ubuntu"
	VERSION="16.04.1 LTS (Xenial Xerus)"
	ID=ubuntu
	ID_LIKE=debian
	PRETTY_NAME="Ubuntu 16.04.1 LTS"
	VERSION_ID="16.04"

I am using the varnish-cache repository for Debian Jessie (as there is none specific for Ubuntu xenial yet, see #36). 

    $ cat /etc/apt/sources.list.d/varnish-cache.list 
    deb https://repo.varnish-cache.org/debian/ jessie varnish-4.1

Yesterday I updated varnish from 4.1.1-1 to 4.1.3-1~jessie on our test environment and shortly after our QA testers found out, that some http headers, Varnish was supposed to add, disappeared. 
It turned out that the installation of the update has overwritten the systemd service config file located under /lib/systemd/system/varnish.service.

Due to the fact, that systemd does not read /etc/default/varnish anymore (see https://bugs.launchpad.net/ubuntu/+source/varnish/+bug/1573561), my daemon specific configuration changes (as malloc for example) were done directly in **/lib/systemd/system/varnish.service**. 

Before the update:

	[Unit]
	Description=Varnish HTTP accelerator
	Documentation=https://www.varnish-cache.org/docs/4.1/ man:varnishd

	[Service]
	Type=simple
	LimitNOFILE=131072
	LimitMEMLOCK=82000
	ExecStart=/usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/titan.vcl -S /etc/varnish/secret -s malloc,4096m
	ExecReload=/usr/share/varnish/reload-vcl
	ProtectSystem=full
	ProtectHome=true
	PrivateTmp=true
	PrivateDevices=true

	[Install]
	WantedBy=multi-user.target

After the update:

	[Unit]
	Description=Varnish Cache, a high-performance HTTP accelerator

	[Service]
	Type=forking

	# Maximum number of open files (for ulimit -n)
	LimitNOFILE=131072

	# Locked shared memory (for ulimit -l)
	# Default log size is 82MB + header
	LimitMEMLOCK=82000

	# On systemd >= 228 enable this to avoid "fork failed" on reload.
	#TasksMax=infinity

	# Maximum size of the corefile.
	LimitCORE=infinity

	ExecStart=/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
	ExecReload=/usr/share/varnish/reload-vcl

	[Install]
	WantedBy=multi-user.target

The problem? The update process asked whether or not to replace /etc/default/varnish (although irrelevant with systemd):

	Configuration file '/etc/default/varnish'
	 ==> Modified (by you or by a script) since installation.
	 ==> Package distributor has shipped an updated version.
	   What would you like to do about it ?  Your options are:
	    Y or I  : install the package maintainer's version
	    N or O  : keep your currently-installed version
	      D     : show the differences between the versions
	      Z     : start a shell to examine the situation
	 The default action is to keep your current version.
	*** varnish (Y/I/N/O/D/Z) [default=N] ? N

But it didn't ask whether or not to replace /lib/systemd/system/varnish.service. 
Please add the same behaviour to the package, ask whether or not to replace the existing  /lib/systemd/system/varnish.service file.

**Comment by fgsch** [comment]
You should not change /lib/systemd/system/varnish.service.  Your changes, if any, should go under /etc/systemd/system and/or /etc/systemd/system/varnish.service.d/. 

Please refer to https://varnish-cache.org/docs/5.0/tutorial/putting_varnish_on_port_80.html#debian-v8-ubuntu-v15-04 and the drop-in mechanism in systemd.unit(5).

**Comment by Napsty** [comment]
OK thanks
