### ISSUE TITLE
Please sign RHEL7 EPEL RPMs

### ISSUE THREAD

**Issue by luyseyal** [varnishcache/pkg-varnish-cache#49]
Original issue: https://github.com/varnishcache/varnish-cache/issues/2119

Varnish is awesome. It would work more nicely with RPM if the RPMs were signed. Please sign RHEL 7 RPMs from your repo (e.g., https://repo.varnish-cache.org/redhat/varnish-4.1.el6.rpm)
## Expected Behavior

RPM signature available.
## Current Behavior

Workaround missing signatures:
`rpm --nosignature -i https://repo.varnish-cache.org/redhat/varnish-4.1.el7.rpm`
## Your Environment

- Version used: 4.1
- Operating System and version: RHEL 7

**Comment by luyseyal** [comment]
@fgsch FYI

**Comment by luyseyal** [comment]
Updated with clarification from sysadmin... We use it via satellite.

**Comment by Dridi** [comment]
We moved packages hosting to packagecloud, please reopen if this is still the case.
