### ISSUE TITLE
${LOGNAME} empty when calling reload-vcl via Debian init script

### ISSUE THREAD

**Issue by watmm** [varnishcache/pkg-varnish-cache#51]
Hey,

I get a "106 Illegal character in VCL name" whenever uuid generates a string beginning with a number and calling reload-vcl via init script or systemctrl

OS: Debian (jessie)
Varnish: 5.0.0-1

See
https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/mgt/mgt_vcl.c 
https://github.com/varnishcache/pkg-varnish-cache/blob/1d5b56f369c1e23637fcd2147d87df5e8d90dcc2/debian/reload-vcl#L42-L48
https://gist.github.com/watmm/5234ddf387e2912852e9a33ad7a37990

sh is a symlink to dash, but i've also tried bash so that's not it.
$(logname) is also empty, but only when calling via init.

Cheers

**Comment by gquintard** [comment]
@watmm , @zstyblik,

would you mind having a look at #52 and see if it fixes your issues?

The new reload-vcl is here:https://raw.githubusercontent.com/varnishcache/pkg-varnish-cache/master/debian/reload-vcl

**Comment by zstyblik** [comment]
@gquintard, it seems to be working, but if you want, I can report back again tomorrow. Thanks!

**Comment by zstyblik** [comment]
@gquintard, please, can you estimate when the package with the fix will be available or which version will it bear? Thank you

**Comment by gquintard** [comment]
@zstyblik : yes, please do report back once you have more info/confidence in the fix.

And I have no idea when we'll see a new release, but someone here may know, let's see if they pop in.

**Comment by zstyblik** [comment]
Fix seems to be working just fine and without issues.

**Comment by Dridi** [comment]
Summoning @ssm

**Comment by watmm** [comment]
Hi,

That makes no difference for me.

Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + printf Error: vcl.load %s %s failed 78d83e05-8da4-4b92-be89-d10cff00d3a1 /etc/varnish/aws-ec2-config-varnish/sw.vcl
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + exitstatus=1
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + [ -z  -o -n 1 ]
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + grep -v ^$ /tmp/78d83e05-8da4-4b92-be89-d10cff00d3a1
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: Illegal character in VCL name ('7')
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: Error: vcl.load 78d83e05-8da4-4b92-be89-d10cff00d3a1 /etc/varnish/aws-ec2-config-varnish/sw.vcl failed
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + rm -f /tmp/78d83e05-8da4-4b92-be89-d10cff00d3a1
Nov 23 14:14:23 varnish-01 reload-vcl[9090]: + exit 1

If i echo "$(env) and call via init.d i get simply:

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LANG=en_US.UTF-8
MAINPID=1705
PWD=/

Does start-stop-daemon sanitise the environment?

**Comment by zstyblik** [comment]
@watmm, have you applied patch from the MR? Because it looks to me like you didn't.

**Comment by watmm** [comment]
My bad, i only downloaded the linked to reload-vcl.
All is well. Cheers!

**Comment by zstyblik** [comment]
By calling `reload-vcl` from command line as logged in user, I've managed to hit:

```
/usr/share/varnish/reload-vcl
Command failed with error code 106
Illegal character in VCL name (':')
Error: vcl.load vcl_root:f436563b-a33b-4a3d-9ac9-38e07ef01357 /etc/varnish/default.vcl failed
```

Replacing `:` with `_` did the trick :|

**Comment by gquintard** [comment]
@zstyblik : I'm not getting how you can have this error. Just to be sure, can you paste the lines setting vcl_label?

Normally, it should be:
```
vcl_label="${LOGNAME}${LOGNAME:+_}${uuid}"
```
so you're variable doesn't make sense in this context.

**Comment by zstyblik** [comment]
@gquintard, I'm with you. I've verified your patch with varnish5 downloaded from varnish-cache.org and it was working. However, we've then switched to varnish5 built by Debian and then this happened.

Here's the patch I've applied and is working under use-cases encountered so far:

```
--- a/debian/reload-vcl	2016-10-13 04:21:04.000000000 +0000
+++ b/debian/reload-vcl	2016-12-07 20:12:13.465508289 +0000
@@ -42,9 +42,9 @@
 if [ -f /proc/sys/kernel/random/uuid ]
 then
     uuid=$(cat /proc/sys/kernel/random/uuid)
-    vcl_label="${LOGNAME}${LOGNAME:+:}${uuid}"
+    vcl_label="vcl_${LOGNAME}${LOGNAME:+_}${uuid}"
 else
-    vcl_label="$($date +${LOGNAME}${LOGNAME:+:}%s.%N)"
+    vcl_label="vcl_$($date +${LOGNAME}${LOGNAME:+_}%s.%N)"
 fi
 
 # Load defaults file
```

Here is the diff between reload-vcl from master branch of this repository and reload-vcl shipped by Debian package:

```
--- reload-vcl  2016-12-20 19:46:59.742244720 +0100
+++ debian/reload-vcl   2016-12-07 06:49:43.000000000 +0100
@@ -42,9 +42,9 @@
 if [ -f /proc/sys/kernel/random/uuid ]
 then
     uuid=$(cat /proc/sys/kernel/random/uuid)
-    vcl_label="${LOGNAME}${LOGNAME:+_}${uuid}"
+    vcl_label="${LOGNAME}${LOGNAME:+:}${uuid}"
 else
-    vcl_label="$($date +${LOGNAME}${LOGNAME:+_}%s-%N)"
+    vcl_label="$($date +${LOGNAME}${LOGNAME:+:}%s.%N)"
 fi
 
 # Load defaults file
@@ -87,7 +87,7 @@
 # Extract the -f and the -T option, and (try to) ensure that the
 # management interface is on the form hostname:address.
 OPTIND=1
-while getopts a:b:CdFf:g:h:i:j:l:M:n:P:p:S:s:T:t:u:Vw: flag $DAEMON_OPTS
+while getopts a:b:CdFf:g:h:i:l:M:n:P:p:S:s:T:t:u:Vw: flag $DAEMON_OPTS
 do
     case $flag in
                f)
```

**Comment by gquintard** [comment]
ok, so debian went for the colon instead of the underscore, that's on them.

**Comment by ssm** [comment]
@gquintard or rather, the debian maintainer (me) forgot to update reload-vcl in the packaging as soon as the script was done.  I'll get a new version in.

**Comment by ssm** [comment]
varnish 5.0.0-6 uploaded to Debian, 

The updated reload-vcl script is now at https://anonscm.debian.org/cgit/pkg-varnish/pkg-varnish.git/tree/debian/reload-vcl
