### ISSUE TITLE
New varnish 5.0.x (Debian) release

### ISSUE THREAD

**Issue by zstyblik** [varnishcache/pkg-varnish-cache#53]
Hello,

I'm not sure how to formulate request politely enough and correctly, but I want to ask for a new Debian release or build. Outstanding bugs which make Varnish 5.0.0 unusable/unreliable for production and are worth of new release(in my opinion and the ones we've encountered so far ... which doesn't mean I'm right):

* https://github.com/varnishcache/pkg-varnish-cache/issues/51 ~ could be solved by just increasing build number, imho
* https://github.com/varnishcache/varnish-cache/issues/2010 ~ requires patch level inc, imho

Thank you and sorry for being pesky :)

**Comment by joshuaspence** [comment]
+1

**Comment by Dridi** [comment]
As far as I know we are not planning further 5.0 releases, and you should get all the fixes in the coming 5.1 in March. Regarding community packages, we only provide "${version}-1" packages for each release but we don't maintain them like a downstream maintainer would: back-porting fixes, adding platform-specific patches...

IMHO the best thing to do now would be to use the scripts we make available in this repo to build yourselves new packages. I'm well aware that it would likely be hard for you to back-port patches, so my advice would be to package the current master branch instead. We have core developers that run master in production that would recommend the same.

All in all, thanks for running bleeding edge Varnish!

I'm keeping this ticket open in case someone else proves me wrong and says that new 5.0 packages will be published.

**Comment by zstyblik** [comment]
*sigh* ok.

**Comment by Dridi** [comment]
@zstyblik fyi we are currently discussing this offline but a 5.0.1 is still unlikely.

I think that @joshuaspence started looking at the master branch if I correctly understand his recent bug reports. In both cases, we really appreciate users using the latest releases/master branch and reporting bugs but we currently don't have the bandwidth to maintain all major releases.

**Comment by zstyblik** [comment]
@Dridi, sure, no problem. We've applied all patches, two of them, we needed. There is not enough courage yet to be running on the bleeding edge ;)

**Comment by denisbr** [comment]
I'm going to close this issue, as 5.1 is where the effort is done now.
