### ISSUE TITLE
4.1 unavailable on stretch

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#54]
With a recent upgrade, Debian stretch now has apt 1.4 which disallows SHA1 signatures for repositories. This means the jessie repo can not be used any longer.

> root@lima:/home/lkarsten# apt-get update
> Hit:1 http://repo.varnish-cache.org/debian jessie InRelease
> Hit:2 http://ftp.no.debian.org/debian stretch InRelease                                                            
> Hit:3 http://ftp.no.debian.org/debian stretch-updates InRelease                                                    
> Err:1 http://repo.varnish-cache.org/debian jessie InRelease                                                        
>   The following signatures were invalid: E98C6BBBA1CBC5C3EB2DF21C60E7C096C4DEFFEB
> [..]
> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://repo.varnish-cache.org/debian jessie InRelease: The following signatures were invalid: E98C6BBBA1CBC5C3EB2DF21C60E7C096C4DEFFEB
> W: Failed to fetch http://repo.varnish-cache.org/debian/dists/jessie/InRelease  The following signatures were invalid: E98C6BBBA1CBC5C3EB2DF21C60E7C096C4DEFFEB
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> 

Expected: jessie packages easily installable on stretch, like they've been up until now.

Before the upgrade, this was only a warning:

> W: http://repo.varnish-cache.org/debian/dists/jessie/InRelease: Signature by key E98C6BBBA1CBC5C3EB2DF21C60E7C096C4DEFFEB uses weak digest algorithm (SHA1)

From the update note:
```
apt (1.4~beta1) unstable; urgency=medium

  Support for GPG signatures using the SHA1 or RIPE-MD/160 hash
  algorithms has been disabled. Repositories using Release files
  signed in such a way will stop working. This change has been made
  due to security considerations, especially with regards to possible
  further breakthroughs in SHA1 breaking during the lifetime
  of this APT release series.

  It is possible (but STRONGLY ADVISED AGAINST) to revert to the previous
  behaviour by setting the options
    APT::Hashes::SHA1::Weak "yes";
    APT::Hashes::RIPE-MD/160::Weak "yes";
  Note that setting these options only affects the verification of the overall
  repository signature.

 -- Julian Andres Klode <jak@debian.org>  Fri, 25 Nov 2016 13:19:32 +0100
```

**Comment by fgsch** [comment]
I will fix this on aptly.

**Comment by fgsch** [comment]
Should be fixed now. Please check again and let me know.

**Comment by lkarsten** [comment]
Confirming that apt-get update on stretch no longer complains about this, and that the repository seems to load as normal. Thanks!
