### ISSUE TITLE
Conflicts warning on RHEL

### ISSUE THREAD

**Issue by hwatts** [varnishcache/pkg-varnish-cache#59]
There seems to be an issue with the packaging of varnish 4.1.4 on RHEL systems. After installing, you get the following warnings:

> yum check
> Loaded plugins: fastestmirror
> varnish-4.1.4-1.el7.x86_64 has installed conflicts varnish-libs: varnish-4.1.4-1.el7.x86_64
> varnish-4.1.4-1.el7.x86_64 has installed conflicts varnish-docs: varnish-4.1.4-1.el7.x86_64
> varnish-4.1.4-1.el7.x86_64 has installed conflicts varnish-debuginfo: varnish-4.1.4-1.el7.x86_64
> Error: check all

It's functional other than the warnings being present. 

I'm not an expert on the RPM spec, but it looks like it both provides these and declares them as conflicts, which doesn't look correct, but I may be barking up the wrong tree...

**Comment by ju55i** [comment]
This really breaks Varnish 4.1 for RHEL7 quite badly. Even the 4.1.3 version is broken because the 4.1.4 provides the the dependencies for that one also.

**Comment by denisbr** [comment]
@ju55i I have installed the packages on multiple EL6 and EL7 hosts without any problems, but please provide more details as to what problems you experience.

This metadata issue will be fixed in the next point release of the package, which is planned this week barring any last minute issues.

**Comment by denisbr** [comment]
The upcoming 4.1.5 release fixes this problem, and will be available shortly.

**Comment by denisbr** [comment]
This issue has been fixed in the 4.1.5 release which is available in the repositories now.
