### ISSUE TITLE
Put sleep between `vcl.load` and `vcl.use` in reload-vcl script

### ISSUE THREAD

**Issue by zstyblik** [varnishcache/pkg-varnish-cache#61]
Hello,

as per discussion in https://github.com/varnishcache/varnish-cache/issues/2195, I suggest to put sleep between `vcl.load` and `vcl.use` in reload-script. Ideally, this should be configurable via ENV variable with some default. 5s worked for me, but I think value will depend on health probe configuration.

Example of suggested patch:
```
--- a/debian/reload-vcl 2016-10-13 04:21:04.000000000 +0000
+++ b/debian/reload-vcl 2016-12-07 20:12:13.465508289 +0000
@@ -149,6 +149,7 @@
     then
        printf "$msg_compile_only" $varnishadm $mgmt_interface $vcl_label
     else
+       sleep 5
        if $varnishadm -T $mgmt_interface -S ${secret} vcl.use $vcl_label
        then
            printf "$msg_use_ok" $vcl_label
```

As for how to make it configurable, eg.:
```
WARMUP_TIME=${WARMUP_TIME:-5}
```

**Comment by denisbr** [comment]
Hi,

Thanks for the suggestion. However I don't think this patch solves the problem in an elegant way. I'm open to discussion here, but to me it seems that introducing this delay will only gloss over the issue in certain scenarios, while introducing delay for all reloads,even when it is not necessary.

If we are to solve the real issue with a change to the reload script, I suggest we find a better, more intuitive way that will work for more cases, and not introduce delay unless needed.

I'll ponder this one a bit more today, and come back to it later.

**Comment by denisbr** [comment]
Working on a patch to the package files that will implement the suggestion, but with a default warmup time of 0 so existing behaviour is unchanged.

**Comment by zstyblik** [comment]
> Working on a patch to the package files that will implement the suggestion, but with a default warmup time of 0 so existing behaviour is unchanged.

@denisbr, sure. It was just an example and the default value of 0, when not specified, makes sense.

**Comment by denisbr** [comment]
This feature is now available in the the 4.1.5 release of the packages.

**Comment by zstyblik** [comment]
Hello @denisbr,

is varnish 5.x covered as well?

Thanks

**Comment by denisbr** [comment]
@zstyblik There has not been any new 5.0 releases today, so not yet.

**Comment by denisbr** [comment]
No 5.x releases done today, so no, not yet.
