### ISSUE TITLE
[DEBIAN] VCL reload script doesn't support available varnishd flags/parameters

### ISSUE THREAD

**Issue by akuznecov** [varnishcache/pkg-varnish-cache#64]
Hello,

Reload script on  ```debian/reload-vcl``` has no idea about new flags/parameters added on 4.1/5.0

http://www.varnish-cache.org/docs/4.1/reference/varnishd.html
http://www.varnish-cache.org/docs/5.0/reference/varnishd.html

for example:
> ```
> -W waiter	Specifies the waiter type to use.
> ```

it leads to warning report during usage

```
# /etc/init.d/varnish reload
[....] Reloading HTTP accelerator: varnishdIllegal option -W
. ok
```

**Comment by Dridi** [comment]
Closing in favor of #70.
