### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/pkg-varnish-cache#66]
It works like this repository needs to be updated after https://github.com/varnishcache/varnish-cache/commit/dd5d18952fb9badd4eb388c98a6da7c3882b0969. Specifically, I am trying to build Varnish from source and the service is failing to start with the following error:

```
CLI result = 300
Error: Child (10967) Pushing vcls failed:
VCL "boot" Failed initialization
Message:
	Creating copy of vmod directors: Permission denied
```

I think that the issue is that `/var/lib/varnish/${NAME}/vmod_cache` is owned by `varnish:varnish`, and is not writable by the `vcache` user.

**Comment by joshuaspence** [comment]
This issue might actually belong in https://github.com/varnishcache/varnish-cache. My first thought was that the Varnish package should probably create this directory with the correct permissions, but looking at the source it seems that Varnish itself creates this directory by calling `VJ_make_vcldir("vmod_cache")`.

**Comment by fgsch** [comment]
I think this deserves attention in the main repo. Mind moving the conversation there?

**Comment by fgsch** [comment]
Nevermind my comment. I see you also opened https://github.com/varnishcache/varnish-cache/issues/2227.

**Comment by denisbr** [comment]
@joshuaspence Is this an issue with the packaging or a varnish-cache issue?

**Comment by joshuaspence** [comment]
I can't reproduce this issue anymore, so it must've been fixed somewhere.
