### ISSUE TITLE
cp: cannot stat 'doc/sphinx/build/html': No such file or directory

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/pkg-varnish-cache#67]
I am trying to build Varnish from source using `dpkg-buildpackage`, but it is currently failing with the following error:

```
dh_install -a --fail-missing
install -o root -g root -m 755 \
	/home/jenkins/workspace/Infrastructure/varnish/debian/reload-vcl \
	/home/jenkins/workspace/Infrastructure/varnish/debian/varnish/usr/share/varnish/reload-vcl
make[1]: Leaving directory '/home/jenkins/workspace/Infrastructure/varnish'
   debian/rules override_dh_installdocs
make[1]: Entering directory '/home/jenkins/workspace/Infrastructure/varnish'
test -d doc/html || cp -pr doc/sphinx/build/html doc/html
cp: cannot stat 'doc/sphinx/build/html': No such file or directory
debian/rules:59: recipe for target 'override_dh_installdocs' failed
make[1]: *** [override_dh_installdocs] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/Infrastructure/varnish'
debian/rules:29: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 2
dpkg-buildpackage: error: debian/rules binary-arch gave error exit status 2
```

I noticed that `sbuild` is used rather than `dpkg-buildpackage` in the `./package-deb`, so I don't know if the upstream is interested in the fix here, but I was able to successfully build the `varnish` package by adding the following target to `debian/rules`:

```
override_dh_auto_build:
    $(MAKE) dist html
```

I will submit a pull request.

**Comment by Dridi** [comment]
Could you please describe how you build Varnish from source? Especially how you gather the source.

As I said in #68 you shouldn't need to rebuild the documentation.

**Comment by joshuaspence** [comment]
Running `dpkg-buildpackage` runs `./debian/rules clean`, which wipes out the generated documentation.

**Comment by Dridi** [comment]
Yet another dpkg mystery to me, I'm leaving this to knowledgeable people. I will shut myself in my rpm fortress :)

**Comment by denisbr** [comment]
@joshuaspence I'm not at a point where all the intricacies of the debhelper system are clear to me, but if ``dh_clean`` is used, it could maybe be better to instruct it to leave the already built docs using ``-Xdoc/sphinx`` or similar?

**Comment by Dridi** [comment]
Closing in favor of #68. People of the DPKG persuasion, please review.
