### ISSUE TITLE
/var/lib/varnish and /var/lib/varnish-plus are created but only the former is used

### ISSUE THREAD

**Issue by fgsch** [varnishcache/pkg-varnish-cache#7]
Any reason for this?

See https://varnish.zendesk.com/agent/tickets/13058.

**Comment by lkarsten** [comment]
This concerns a packaging bug in the similarly named Varnish Plus packaging repository.

A fix was pushed in commit 5b83b89e9 there.

**Comment by fgsch** [comment]
Moved to https://github.com/varnish/pkg-varnish-plus/issues/18.

**Comment by fgsch** [comment]
Moved to the correct repository.
