### ISSUE TITLE
custom pidfile causing restart to fail

### ISSUE THREAD

**Issue by mgla** [varnishcache/pkg-varnish-cache#72]
# Steps to reproduce:

Fire up a new Ubuntu 14.04 instance (I used an AWS Ubuntu image):

```
add-apt-repository "deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-4.1"
apt-get update
apt-get install varnish --force-yes -y
sed -i 's#-s malloc,256m"#-P /run/varnishd.pid \\\n             -s malloc,256m"#' /etc/default/varnish
service varnish restart
```

# Expected behavior

Clean restart

# Actual behavior

```
 * Stopping HTTP accelerator varnishd
No /usr/sbin/varnishd found running; none killed.
   ...fail!
 * Starting HTTP accelerator varnishd
   ...fail!
Error: Cannot open socket: :6081: Address already in use
```

# Additional details:

The sed just adds the -P parameter to /etc/default/varnish:

```
DAEMON_OPTS="-a :6081 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -P /run/varnishd.pid \
             -s malloc,256m"
```

Took me a while to track it down. I recently opened this report: https://github.com/varnishcache/pkg-varnish-cache/issues/71 but was wrong in my assessment.

**Comment by mgla** [comment]
Pinging @denisbr  I managed to reproduce it, but it was not what I expected.

**Comment by denisbr** [comment]
Does the varnish use have sufficient privileges on the /run directory?

**Comment by denisbr** [comment]
Also, could you dump the complete resulting /etc/default/varnish?

**Comment by mgla** [comment]
Complete /etc/default/varnish:

```
# Configuration file for Varnish Cache.
#
# /etc/init.d/varnish expects the variables $DAEMON_OPTS, $NFILES and $MEMLOCK
# to be set from this shell script fragment.
#
# Note: If systemd is installed, this file is obsolete and ignored.  You will
# need to copy /lib/systemd/system/varnish.service to /etc/systemd/system/ and
# edit that file.

# Should we start varnishd at boot?  Set to "no" to disable.
START=yes

# Set WARMUP_TIME to force a delay in reload-vcl between vcl.load and vcl.use
# This is useful when backend probe definitions need some time before declaring
# configured backends healthy, to avoid routing traffic to a non-healthy backend.
#WARMUP_TIME=0

# Maximum number of open files (for ulimit -n)
NFILES=131072

# Maximum locked memory size (for ulimit -l)
# Used for locking the shared memory log in memory.  If you increase log size,
# you need to increase this number as well
MEMLOCK=82000

DAEMON_OPTS="-a :6081 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -P /run/varnishd.pid \
             -s malloc,256m"


```

**Comment by mgla** [comment]
/run/varnishd.pid is actually the default pid file.

**Comment by denisbr** [comment]
This is definitely not a varnish-cache issue, and while it is caused by packaging and the initscripts, it's not really a bug per-se.

The issue is that the initscript has it's own pidfile handling: 
https://github.com/varnishcache/pkg-varnish-cache/blob/master/debian/varnish.init#L23-L52

If you want to use an alternative pidfile path / filename, the correct way to do this in debian is to add a ``PIDFILE`` option to the ``/etc/default/varnish`` file.

```
PIDFILE="/run/mycustompidfile.pid
```

This will override the predefined PIDFILE in the initscript, and make all interaction with the script work as expected.

**Comment by mgla** [comment]
@denisbr Actually, the init script ignores externally set PIDFILE and hardcodes it to /run/varnishd.pid:

```
[..]
SERVICE=varnishd
[..]
PIDFILE=/run/$SERVICE.pid
[..]
```

**Comment by denisbr** [comment]
@mgla I did the work to test all scenarios that I mentioned in local environments before closing.

**Comment by mgla** [comment]
@denisbr  You were absolutely right. I believieve this can be closed.

**Comment by denisbr** [comment]
Thanks for confirming, leaving the issue closed :)
