### ISSUE TITLE
Varnish using system.d reloads config from /etc/default/varnish under Ubuntu 16.04

### ISSUE THREAD

**Issue by anabadce** [varnishcache/pkg-varnish-cache#76]
I think I found a bug/problem while trying to reload Varnish running under Ubuntu 16.04 LTS.

The problem seems to be that Varnish service starts using the configuration from `/lib/systemd/system/varnish.service` while the reload reads the config from `/etc/default/varnish`

- Fact: `/lib/systemd/system/varnish.service` contains Varnish service config when it starts

- Problem: file above defines `/usr/share/varnish/reload-vcl` as script to reload and this file uses `/etc/default/varnish` to re-read the config. Inconsistency is that restart and reload grab config from diferent location.

Problem is obvious if you start Varnish using a different file than *default.vcl*.

## How to replicate

1. Install Varnish in Ubuntu 16.04 following https://packagecloud.io/varnishcache/varnish41/install
2. Install Nginx (so you have a backend to test)
3. Create own Varnish config in `/etc/varnish/my.vcl` (copy from `/etc/varnish/default.vcl`)
4. Change `/etc/varnish/my.vcl` so backend is port 80 (nginx default)
```
.port = "80";
```

5. Change `/lib/systemd/system/varnish.service` so it uses `/etc/varnish/my.vcl` instead of *default.vcl*
```
sudo systemctl daemon-reload
sudo service varnish restart
```

6. You should now get the Nginx default page via Varnish: 
```
curl http://localhost:6081 -v | head
```

7. Now reload Varnish: 
```
sudo service varnish reload
```

9. This test will *FAIL* with backend failure (as config has been reloaded with *default.vcl*):  
```
curl http://localhost:6081?nocache -v | head
```

**Comment by denisbr** [comment]
Hi,

Thanks for a  very thorough and nicely detailed bugreport. We're currently in the middle of revamping the vcl-reload mechanism. Could you try the updated reloadscript from https://github.com/varnishcache/pkg-varnish-cache/pull/70 [[downloadable file](https://raw.githubusercontent.com/Dridi/pkg-varnish-cache/f003c729eda00a3498f6b2b0af3c7a802987ec0e/varnishreload)] and see if this fixes the problem?
It should, as it does not depend on a hard-coded VCL file name, and instead dynamically finds the correct VCL to reload based on active configuration.

You would have to change your .service to use the new reloadscript:

```
ExecReload=/PATH/TO/varnishreload
```

If you report back with the result, it will be helpful.

Regards
Denis

**Comment by Dridi** [comment]
I would also recommend using the `-m` option in your `ExecReload` command to automatically discard old reloads.

https://github.com/Dridi/pkg-varnish-cache/blob/f003c72/varnishreload#L43-L66

**Comment by anabadce** [comment]
Hi Dridi and Denis and thank you for replying so quickly.

I can confirm the new reload script works fine to me as well as the `-m` option to discard old reloads, nice work!

The only thing I noticed is the reload failing if you try reloading twice within the same second:
```
Jun 07 03:24:25 varnishdev varnishreload[7397]: Command failed with error code 106
Jun 07 03:24:25 varnishdev varnishreload[7397]: Already a VCL program named reload_20170607_032425
```

Not something I would happen often I guess it would be good to take it into account.

Angel

**Comment by Dridi** [comment]
> nice work!

Thanks!

> Not something I would happen often I guess it would be good to take it into account.

That is technically taken into account: the script gracefully fails with an error message.

**Comment by Napsty** [comment]
Bug affects me too (Varnish 5.1.2-1 on Ubuntu 16.04.2 LTS. 
I can confirm the workaround using "varnishreload" as systemd ExecReload works.

    # cat /etc/systemd/system/varnish.service |grep ExecReload
    #ExecReload=/usr/share/varnish/reload-vcl
    ExecReload=/usr/sbin/varnishreload

Thanks for that hint!
Hope one of the next package updates will contain this workaround, too.

**Comment by Napsty** [comment]
Bug affects me too (Varnish 5.1.2-1 on Ubuntu 16.04.2 LTS. 
I can confirm the workaround using "varnishreload" as systemd ExecReload works.

    # cat /etc/systemd/system/varnish.service |grep ExecReload
    #ExecReload=/usr/share/varnish/reload-vcl
    ExecReload=/usr/sbin/varnishreload

Thanks for that hint!
Hope one of the next package updates will contain this workaround, too.

**Comment by denisbr** [comment]
@Napsty Thanks for the feedback. This is actually meant not as a workaround, but as the future solution to the current issues. Good to hear it works out for you.

**Comment by Dridi** [comment]
@anabadce, @Napsty: please try the latest version of the script in https://github.com/varnishcache/pkg-varnish-cache/pull/70#issuecomment-336050706 and report there if it still works fine or breaks. I'm closing this issue now.

Thanks for testing the previous script!
