### ISSUE TITLE
Debian Stretch (9) support?

### ISSUE THREAD

**Issue by geerlingguy** [varnishcache/pkg-varnish-cache#78]
I'm glancing around in the packagecloud.io repositories, but I'm not able to find any packages for Debian 9 'Stretch'; I'm trying to get some things updated to support Debian 9, but right now it seems Varnish is the main package that's unavailable through packagecloud (it seems to only be available through system repos, is that correct?

**Comment by geerlingguy** [comment]
See a failed build here: https://travis-ci.org/geerlingguy/ansible-role-varnish/jobs/246953335

```
The repository 'https://packagecloud.io/varnishcache/varnish51/debian stretch Release' does not have a Release file.
```

**Comment by denisbr** [comment]
I started the process of getting our packaging systems ready for stretch last week, and I'm hoping to have some early builds ready soon. You're correct that the official repositories do not yet contain stretch packages.

**Comment by denisbr** [comment]
Hi @geerlingguy, I just completed the push of the first attempt at stretch packages to packagecloud.io:
https://packagecloud.io/app/varnishcache/varnish41/search?filter=all&q=&dist=debian%2Fstretch

I have not done a lot of testing with these packages yet, please report back.

**Comment by geerlingguy** [comment]
It looks like it's working on my Drupal VM builds! https://travis-ci.org/geerlingguy/drupal-vm/jobs/247773638#L2288-L2337

It looks like the full build is passing on my upstream role, too (https://travis-ci.org/geerlingguy/ansible-role-varnish/jobs/248557698), so I'd say it's good to go! Thanks for the quick work on this.

**Comment by geerlingguy** [comment]
I'll go ahead and close this issue, as it seems to be working great in all my testing.
