### ISSUE TITLE
systemd: varnishncsa starts too fast

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/pkg-varnish-cache#79]
When enabling varnish and varnishncsa with systemctl, upon reboot, varnishncsa will fail, as it tries to start varnishncsa immideately after varnishd has started. varnishd uses some time to init before it opens its vsm file, and thus varnishncsa fails.

A simple fix is just to add a delay to either varnish (ExecStartPost) or varnishncsa (ExecStartPre), or make varnishncsa restart until it succeeds or gives up (Restart=on-failure). A more "correct" approach would be to find some resource that is made available when varnishd has started up properly, and that systemd can probe for.

Bugzilla report ticket: https://bugzilla.redhat.com/show_bug.cgi?id=1464355

**Comment by Dridi** [comment]
We have another potential solution that needs to be tested further, it could work with both systemd via its notification system or any other init system with a little tweak.

However, you can mitigate this using the `-t` option in `varnishncsa`.

**Comment by Dridi** [comment]
I had a quick look at bugzilla, and this doesn't apply for 4.0, so your suggested workaround is probably the best solution for now. Please note it's EOL, and I'm aware of el/epel's lifecycle. However according to the guidelines it might be OK to break epel7 since Varnish 4.0 is dead upstream ; I'd need to double check but consider upgrading if this is allowed.

**Comment by ingvarha** [comment]
EPEL tries hard to act like RHEL, ie. no updates that are not API and ABI compatible, including configuration file format changes. According to the EPEL updates policy , there must be a really serious reason to deviate from this. A dead upstream version is not enough, while a major security hole might force an update.

From https://fedoraproject.org/wiki/EPEL_Updates_Policy :
(...)
*  All updates should strive to avoid situations that require manual intervention to keep the package functioning after update. 
* Major updates with changes to user experience are to be avoided. If they cannot be avoided, the EPEL incompatible upgrades policy MUST be followed. This includes two separate announcements to the epel-announce mailing list.
(...)

In some rare cases, exceptions will need to be made. Bring your case before the EPEL SIG at one of the weekly meetings and/or the epel-devel mailing list. Possibly grounds for exception might include:

* Serious security issue that cannot be backported to the existing version, so a new major version is required. 
* Serious bugs that cannot be fixed in the existing version. 

In cases of major disruption, EPEL updates will looked to be done along with Red Hat Enterprise Linux minor releases (6.1, 6.2, 6.3) so as to allow for longer testing or differing beta testing.

**Comment by Dridi** [comment]
As 4.0 has been EOL for a long time, I'm closing this.
