### ISSUE TITLE
Improve RPM Provides for VRT ABI level

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#8]
There are some additional Provides added by the find-provides script during package builds for repo.varnish-cache.org. These add the VRT (Varnish RunTime) markers to the package, for vmod packages to depend on.

For 4.1.1-2 this set of Provides exist:

```
[lkarsten@el7 el7]$ rpm -qp --provides varnish-4.1.1-2.el7.x86_64.rpm 
varnish = 4.1.1-2.el7
varnish(x86-64) = 4.1.1-2.el7
varnishabi-strict-66bb824
varnishabi-3.1
```

Originally raised on the EPEL package in https://bugzilla.redhat.com/show_bug.cgi?id=1303543#c6 , Dridi asks if shouldn't instead be:

```
varnish(abi) = 3.1
varnish(abi-strict) = aabbccd
```

because it is more redhat-y and possibly so that it is possible to do a numerical compare on it. (so a vmod built against 3.1 and install on 3.2, as planned)

The current Provide has been there for quite a while. I believe I looked at this before extending it with abi-strict a few years back, but I don't remember any details any more.

**Comment by lkarsten** [comment]
I wonder if our experiences with adding versioned Require's towards a virtual package influences this.

Previously we've had to change "Requires: varnish > 4.0.2r2" back to just "Requires: varnish" on some VCP/Plusproducts, because VCP with its different package name (but added "Provides: varnish") broke a dependency solver on some EL version.

I haven't checked, this may be an entirely separate issue.

**Comment by dmatetelki** [comment]
Fixed in the weekly branch and packages and in the upcoming 6.1 release.
