### ISSUE TITLE
RFC: How to handle systemd vs non-systemd debian/ubuntu packaging

### ISSUE THREAD

**Issue by denisbr** [varnishcache/pkg-varnish-cache#80]
Using dh-systemd in the debian packaging, #74, will make the debs behave better on systemd enabled Debian/Ubuntu releases (stretch, xenial).
However, simply adding in dh-systemd breaks the packaging for all the older versions of said distributions. 

The workflow for debian packages is:
* Grab dist tarball
* Grab the debian/ metadata from pkg-varnish-cache
* Build a source package
* Loop over the distribution-version set and sbuild on each target

Thus, my attempts at modifying the ``debian/control`` and ``debian/rules`` files in the distribution loop fails, and I need another approach.

So far the best idea I've come up with is simply splitting the build-job into two, a non-systemd and a systemd job, each handling the relevant distros. But I might be missing a better way, and would like to get some input before proceeding. Ideally it would simply be handled in the ``package-deb`` script, but after having had a couple of misses in that direction, I'd rather think it over again.

Maybe either @Dridi or @ssm could consider the issue?

**Comment by denisbr** [comment]
Or maybe @fgsch ?

**Comment by denisbr** [comment]
I'll elaborate on the "breaks" part here too.
Adding the ``dh-systemd`` dependency to ``debian/control`` will cause the older distros to fail when building the package, as that package isn't available.
I tried adding dh-systemd via other repositories, as it should ideally be a build-dep, however, using dh-systemd incurs a dependency on ``init-system-helpers`` which again is not available on the systems in question, so that option isn't going to work.

The only sensible way is to build with and without dh-systemd on the relevant targets.

**Comment by stephenreay** [comment]
FYI this may actually affect Debian from Wheezy (when systemd became available) and most certainly Jessie (when systemd became default). 

Also, isn't this only an issue that affects the *build* environment, rather than the run environment? For Debian, dh-systemd is available in backports. For Ubuntu, it's in the main repo from Trusty (14.04) - what versions are you building on that this is breaking?

**Comment by denisbr** [comment]
@stephenreay As I mentioned, I did also try operating under the assumption that it would be a build-dep, but failed. The problematic distros were Ubuntu/Precise and Debian/Wheezy. In Precise, ``dh-systemd`` was not available even in backports, and neither was ``init-system-helpers`` which is the resulting additional dependency when building with dh-systemd.

I'd rather focus on the way to enable both builds with and without dh-systemd though, I used quite some time yesterday testing this, so I'm confident there is no easy way to make building with ``dh-systemd`` on the old distros work.

**Comment by stephenreay** [comment]
Hey @denisbr,

So is Precise still actually supported? It's not even covered by Ubuntu LTS any more. 

Is there something about the build env I don't know, that makes the wheezy changes (adding backports) too hard to manage?

**Comment by denisbr** [comment]
https://wiki.ubuntu.com/Releases Precise just passed EOL cutoff, and I'd rather not kill it just yet. 
Again, I'd prefer if the focus of this discussion was on how to do the split builds.

**Comment by denisbr** [comment]
I split the jobs, and used a conditional for the known problematic distros in ``package-deb``.
Currently building the new packages, and will test both versions.

**Comment by denisbr** [comment]
I've considered the issue, and as everyone is away, I just decided to move forward with the split jobs, and split versions of the relevant files. 

These distros will be build without ``dh-systemd``:

- Debian Wheezy
- Ubuntu Precise
- Ubuntu Trusty

These will be build with ``dh-systemd``:

- Debian Jessie
- Debian Stretch
- Ubuntu Xenial
