### ISSUE TITLE
Heads-up: no more dist archives

### ISSUE THREAD

**Issue by Dridi** [varnishcache/pkg-varnish-cache#82]
With the sunset of https://repo.varnish-cache.org we will likely no longer build and host dist archives as this seems to be the consensus. Instead, we will need autotools during packaging and get source tarballs directly from gtihub.

For example:

https://github.com/varnishcache/varnish-cache/releases/tag/varnish-5.1.3

A worthy note for downstream distributors, Github doesn't generate deterministic archives so they may vary across downloads. We will also lose the ability to [sum](https://repo.varnish-cache.org/source/SHA256SUM) and [sign](https://repo.varnish-cache.org/source/SHA256SUM.gpg) the sources.

**Comment by Dridi** [comment]
Not wanting to throw FUD around Github, I couldn't find in my emails evidence that generated source archives were non-deterministic. However, I found in an old thread (I can find it in the Fedora archive if anyone is interested) that Github used to generate archives differently for tags and commit hashes (and tag archives would  vary over time). I said "used to" because after some testing it no longer seems to be the case. The problem I had in mind seems to have only occurred with the late Google Code.

There is still the possibility that this would break in the future, but the decision is to do something about it (the hypothetical) then. As for signing, @fgsch is going to look at how FreeBSD/OpenBSD ports deal with that when they rely on Github source archives.

In any case, we will need to handle this change in the official packaging.

**Comment by nigoroll** [comment]
Not a problem to continue hosting repo.v-c.org

**Comment by denisbr** [comment]
@nigoroll What do you mean with that?
As far as I gathered, the tarballs will now be picked from Github, and packages will be over at Packagecloud as they've been for a while.

**Comment by denisbr** [comment]
@nigoroll I'll expand a bit on that. As long as we deal with the packaging, we want a simple and easy to use interface to repo management, which packagecloud provides, and aptly/rrrrak etc do not.

**Comment by Dridi** [comment]
I think @nigoroll is telling us he'd keep hosting repo.v-c.o for source tarballs, not packages. That would at least help maintain the current source releases, but we definitely don't want to keep hosting RPM/Deb packages there since packagecloud has been our official host for the repositories for 4.1.something onward.

At least we wouldn't have to change anything in pkg-varnish-cache, same would go for downstream distributors.

Best of both world for me if that's what @nigoroll is proposing.

**Comment by denisbr** [comment]
@Dridi @nigoroll I've mentioned this before, and hosting the tarballs is not the issue in my book. If there are issue(s) preventing the use of Github tarballs, hosting the source tarballs somewhere is the least of our problems, we have systems that are fine with serving those.

It's the hosting of Apt/Yum repos that is an issue due to the moving parts that are involved in generating and maintaining the repository metadata.

**Comment by Dridi** [comment]
Sorry for the confusion @denisbr, I initially opened this ticket to track the need to change packaging if we switch to Github tarballs.

**Comment by denisbr** [comment]
@Dridi No worries, I just wanted to make it clear what we can do and cannot do.

**Comment by Dridi** [comment]
To clarify, my understanding (and presumable others' too when we discussed this on IRC) was a complete shutdown of that domain.

**Comment by denisbr** [comment]
So therein lies the misunderstanding. It's the "repo" bit in repo.varnish-cache.org we need to kill. Serving tarballs from some url is not an issue.

**Comment by Dridi** [comment]
@denisbr I see that now releases are available on the main website, however directory listing is forbidden for downloads and we currently don't provide signatures for release archives. Should I open a new issue in the homepage repo instead?

**Comment by nigoroll** [comment]
thank you to @Dridi for understanding exactly what I tried to say :)

**Comment by denisbr** [comment]
@Dridi I think the current setup with the index of releases via web (with signatures on the individual webpages) is what we will have.
The pattern is rather easy, not sure how much a plain old directory-listing will improve this.
If you think there is something to improve, I think opening an issue on the homepage repo is the right thing to do!
