### ISSUE TITLE
init script for restart seems to use status_of_proc incorrectly

### ISSUE THREAD

**Issue by fgsch** [varnishcache/pkg-varnish-cache#83]
## Expected Behavior
for restart (sudo service varnish restart),
status_of_proc should check if process exists. 

- If it **does**, stop process and then start the process (checking configtest during start init script)
- if it **doesn't**, check configtest and then start the process

## Current Behavior
- If process **does exist**, check configtest and then try to stop/start process
- If it **doesn't exit**, stop process and then start the process (checking configtest during start init script)

this causes a failure because the configtest will check if the varnish port is open and fail seeing that it is occupied (by current varnish process)

## Possible Solution
```
restart|force-reload)
   #this if statement evaluates as true when process is found
   if status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" 1>/dev/null; then
      echo ${PIDFILE} ${DAEMON} ${SERVICE}
      if ! configtest; then
         log_failure_msg "Syntax check failed, not restarting"
         exit 1
      fi
   fi
```

but it should be like:
```
restart|force-reload)
   #this statement will now resolve correctly by negating the status_of_proc output
   if ! status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" 1>/dev/null; then
      echo ${PIDFILE} ${DAEMON} ${SERVICE}
      if ! configtest; then
         log_failure_msg "Syntax check failed, not restarting"
         exit 1
      fi
   fi
```

## Steps to Reproduce (for bugs)
1. install varnish
2. sudo service varnish start
3. sudo service varnish restart

## Your Environment
ubuntu 14.04

**Comment by fgsch** [comment]
Moved from https://github.com/varnishcache/varnish-cache/issues/2384.
cc @rdonahoe-placed

**Comment by denisbr** [comment]
@rdonahoe-placed I assume this is Varnish 5.x?

**Comment by denisbr** [comment]
I checked, and yes this is indeed 5.x. 

The main issue here isn't the reload/configtest logic, but rather the behaviour change in ``-C`` between Varnish 4 and 5. It's been filed as a bug in varnishcache: https://github.com/varnishcache/varnish-cache/issues/2316 
It should be possible to configtest even if varnishd is running. 

The logic in the initscript is meant like this:

* Check if varnishd is running
  * If it is running, do a configtest before stop and restart, to avoid restarting when there is an invalid VCL preventing restart.
  * If it is not running, simply perform the restart, and let the start action display the error if any.

I'll close this issue as a duplicate, as we already have #75 open for this.
