### ISSUE TITLE
After=network-online.target

### ISSUE THREAD

**Issue by SteveKm1** [varnishcache/pkg-varnish-cache#87]
Hello all,

I am writing you regarding the issue I experiencing after one of the latest Red hat release.

Regarding the configuration file "/usr/lib/systemd/system/varnish.service" varnish starts after network begin with start process : 
"After=network.target"

This makes big troubles to the customer websites after reboot of systems. 
Our network is taking bit longer to start(30sec) but varnish doesn't depend on it as it needs only see network starting. So after network begin with start(30sec) varnish also starts(5sec).
That makes varnish fail as it needs network up before starting itself.

For that should be used : 
"After=network-online.target"

After using this correct property everything is okay after boot process - varnish waits till network is up and then starts itself.
Unfortunately varnish update leads to rewrite this property back to old one.(connected by my non-proper changes to config file)

Is it possible to amend this property to "After=network-online.target" from old one as default?

I think it could be the proper setup for the service for future function and would really help me and our customer.

As far as I know targets changed just few RHEL7 releases ago where online property was included in service config files. Most of network dependent services has changed this property as the release came out. Would be great having varnish changed that too.

Thank you very much in advance.

Kind regards,

Stefan

**Comment by Dridi** [comment]
We should look at our systemd platforms and see the implications of using this target. I can have a look at el7 and let others look at the debian systems.

Thanks @SteveKm1 for reporting this twice! The workaround for you is to copy and edit the service file in your `/etc` tree.

**Comment by Dridi** [comment]
Closing, as #94 will apply this change. Thanks again!
