### ISSUE TITLE
Using multiple addresses in varnishd options fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by gbentley** [varnishcache/pkg-varnish-cache#90]
## Description
The [Varnishd reference page](https://varnish-cache.org/docs/4.0/reference/varnishd.html) states that "Multiple listening addresses and ports can be specified as a whitespace or comma -separated list.". Doing this with whitespace in Ubuntu 16.04 fails when viewed via _sudo systemctl status varnish.service_ with **"Error: Too many arguments (:81...)"** and using comma-separated args results in **"Error: Unknown protocol ':81'"**.

## Steps to replicate:

1. Using Ubuntu 16.04, follow steps to configure the server using the [Putting Varnish on Port 80](https://varnish-cache.org/docs/trunk/tutorial/putting_varnish_on_port_80.html#debian-v8-ubuntu-v15-04), and instead of ":80" use ":80,:81" or ":80 :81".

All suggestions welcome!

**Comment by gquintard** [comment]
Hi, pretty sure you are running 4.1 and looking at the 4.0 doc. Syntax changed between the two.

https://varnish-cache.org/docs/4.1/reference/varnishd.html

**Comment by gbentley** [comment]
Thanks @gquintard - you're correct!
