### ISSUE TITLE
EL6 Packages missing from packagecloud.io ?

### ISSUE THREAD

**Issue by aarrowood** [varnishcache/pkg-varnish-cache#93]
The package directory for the EL 6 packages ( https://packagecloud.io/varnishcache/varnish52/el/6/ ) appears to be empty? Are packages no longer being built for EL 6 ?

**Comment by denisbr** [comment]
Packagecloud doesn't really operate with a directorystructure like that, the packages are available, although I recommend you use the varnish5 repository instead:

https://packagecloud.io/app/varnishcache/varnish52/search?q=&filter=all&dist=el%2F6
https://packagecloud.io/app/varnishcache/varnish5/search?q=&filter=all&dist=el%2F6
