### ISSUE TITLE
Missing varnish-modules makes installation harder

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#95]
Hi.

Today I was planning to upgrade a Ubuntu 17.04 artful server from the 5.0.0 version on it to 5.2.1.

The main reason for this is that the packaging on 17.04 does not have "systemctl reload varnish". I was hoping the latest from packagecloud had that fixed, but I didn't get that far.

Issue experienced: missing varnish-modules package makes this difficult, see log below.

Expected: smooth and simple upgrade.

Would it be possible to add varnish-modules to this repo as well?

```
# apt install varnish
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.13.0-16 linux-headers-4.13.0-16-generic linux-image-4.13.0-16-generic linux-image-extra-4.13.0-16-generic
Use 'apt autoremove' to remove them.
Suggested packages:
  varnish-dev
The following packages will be REMOVED:
  libvarnishapi1 varnish-modules
The following packages will be upgraded:
  varnish
1 upgraded, 0 newly installed, 2 to remove and 7 not upgraded.
Need to get 2,398 kB of archives.
After this operation, 8,722 kB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
root@hostname:/etc/apt/sources.list.d#
```

```
# apt policy varnish
varnish:
  Installed: 5.0.0-7.1
  Candidate: 5.2.1-1~xenial
  Version table:
     5.2.1-1~xenial 500
        500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
     5.2.0-1~xenial 500
        500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
     5.1.3-1~xenial 500
        500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
     5.1.2-1 500
        500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
     5.1.1-1 500
        500 https://packagecloud.io/varnishcache/varnish5/ubuntu xenial/main amd64 Packages
 *** 5.0.0-7.1 500
        500 http://no.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by lkarsten** [comment]
Hi, thanks for following up.

As far as I know, VS with community hat on, has never packaged varnish-modules.

In Debian there is a varnish-modules package, built against Varnish Cache 5.1.1 that was current when they cut the latest testing and/or stable. (was it called buster? I'm out of touch)

These packages ended up in the ubuntu distribution that I was using, and when upgrading to a more recent Varnish Cache I ran into the upgrade issue mentioned above.

**Comment by Dridi** [comment]
This is VIP 20 material.

**Comment by lkarsten** [comment]
That is of course an option, but not one that improves the use of Varnish Cache.

**Comment by lkarsten** [comment]
Hi all. Found this while reviewing old issues and PRs.

If I read the lacking enthusiasm from the official packagers of Varnish Cache correctly, this will not happen.

If you have 5.0.0 (or currently: 6.0, in the future 6.1, and so on) and want to upgrade to latest community packages, you must build varnish-modules for yourself, or live with quite basic functionality in VCL. VCL is the main reason to run Varnish over other caches.

At some point another discussion about merging the commonly used parts of varnish-modules into into core. There is close to zero upkeep on keeping these ~10 files working in core, and there is so much wasted effort by users in repackaging them a thousand times over.

This is getting ridiculus.

cc @bsdphk @nigoroll 

-Lasse
