### ISSUE TITLE
reload script does not discard old VCLs

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/pkg-varnish-cache#96]
Issue: when using "systemctl reload varnish" a lot, the list of cold VCLs will grow and grow.

Expected: old stale VCL would be removed automatically.

Suggestion: Add discarding of cold VCLs, unless disabled, to reload-vcl.

Not considered: a use case where you use systemctl reload varnish, but want to keep a cold VCL around. Matching on the vcl naming scheme used by reload-vcl could perhaps avoid discarding those.

For anyone looking for a workaround, this script and an additional ```ExecReload=/usr/local/sbin/discard-old-vcls``` line in the systemd service definition seems to work.
  
```
#!/bin/sh
set -o errexit

COLD_VCLS=$(varnishadm vcl.list | awk '/auto\/cold/ {print $4}')
for vclname in $COLD_VCLS; do
	echo "Discarding $vclname"
	varnishadm vcl.discard $vclname 1>/dev/null
done;
```

Seen on: 5.2.1 packages from packagecloud on ubuntu. (xenial builds)

**Comment by Dridi** [comment]
Better workaround is to import `varnishreload` from #70 that works on both Debian and Red Hat derivatives and is what we ship for all platforms from Varnish 6 onward. ;-)

https://github.com/varnishcache/pkg-varnish-cache/blob/6.x/systemd/varnishreload#L46-L74

**Comment by lkarsten** [comment]
Hi.

Thanks for replying. I knew I had read something about this somewhere, but couldn't find it. In any case, I'm not running 6.0 in production any time soon, and I suspect that applies to many others as well.

**Comment by Dridi** [comment]
Take a copy of the script, it works with Varnish 4.1 and later!
