### ISSUE TITLE
Varnish 6.0 for Debian 8 / Jessie

### ISSUE THREAD

**Issue by jonashrem** [varnishcache/pkg-varnish-cache#97]
Any plans on building varnish 6.0 for Debian 8?

Debian 8 has still LTS support for 2 further years https://wiki.debian.org/LTS

**Comment by dmatetelki** [comment]
Hi Jonas, 

Varnish Software provides packages for VC-6.0 on EL7, debian-stretch and ubuntu-xenial/bionic.

We dropped the support for non-systemd distributions on the 6.x branch, but if you use pkg-varnish-cache's 4.x branch you probably won't have much issues creating Jessie packages locally.

**Comment by jonashrem** [comment]
Debian 8 is systemd based ;)
